//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  Default = 0,
  Gallary = 1,
}

export const AbilityEntityVisibleReason: EnumDefault = {
  __signed: true,
  types: types,
}
