//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  NONE = 0,
  FINISH = 1,
}

export const ActivityGroupLinkRewardType: EnumDefault = {
  __signed: true,
  types: types,
}
