//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  STAGE_TYPE_NONE = 0,
  STAGE_TYPE_RAFT = 1,
  STAGE_TYPE_SAIL = 2,
  STAGE_TYPE_DOWN_HILL = 3,
}

export const ActivityIslandPartyStageType: EnumDefault = {
  __signed: true,
  types: types,
}
