//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  CODEX_SUBTYPE_ELEMENTAL = 0,
  CODEX_SUBTYPE_HILICHURL = 1,
  CODEX_SUBTYPE_ABYSS = 2,
  CODEX_SUBTYPE_FATUI = 3,
  CODEX_SUBTYPE_AUTOMATRON = 4,
  CODEX_SUBTYPE_HUMAN = 5,
  CODEX_SUBTYPE_BEAST = 6,
  CODEX_SUBTYPE_BOSS = 7,
  CODEX_SUBTYPE_AVIARY = 8,
  CODEX_SUBTYPE_ANIMAL = 9,
  CODEX_SUBTYPE_FISH = 10,
  CODEX_SUBTYPE_CRITTER = 11,
}

export const AnimalCodexSubType: EnumDefault = {
  __signed: true,
  types: types,
}
