//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  Enter = 1,
  EnterAndStay = 3,
}

export const BattleFervorStateIDTriggerType: EnumDefault = {
  __signed: true,
  types: types,
}
