//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  Normal = 0,
  Character = 1,
}

export const BillboardOffsetType: EnumDefault = {
  __signed: true,
  types: types,
}
