import { EnumDefault } from "."

enum types {
  BLOSSOM_REFRESH_NONE = 0,
  BLOSSOM_REFRESH_SCOIN = 1,
  BLOSSOM_REFRESH_WEAPON = 2,
  BLOSSOM_REFRESH_EXP = 3,
  BLOSSOM_REFRESH_CRYSTAL = 4,
  BLOSSOM_REFRESH_INFUSED_CRYSTAL = 5,
  BLOSSOM_REFRESH_DRAGON_SPINE_A = 6,
  BLOSSOM_REFRESH_DRAGON_SPINE_B = 7,
  BLOSSOM_ISLAND_SENTRY_TOWER_A = 8,
  BLOSSOM_ISLAND_SENTRY_TOWER_B = 9,
  BLOSSOM_ISLAND_BOMB = 10,
  BLOSSOM_REFRESH_BLITZ_RUSH_A = 11,
  BLOSSOM_REFRESH_BLITZ_RUSH_B = 12,
}

export const BlossomRefreshType: EnumDefault = {
  __signed: true,
  types: types,
}
