//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  BONUS_COMMON = 0,
  BONUS_XIANGLING = 1,
  BONUS_BABALA = 2,
}

export const BonusActivityType: EnumDefault = {
  __signed: true,
  types: types,
}
