//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  COMPOUND_NONE = 0,
  COMPOUND_COOK = 1,
  COMPOUND_PLACEHOLDER_2 = 2,
}

export const CompoundType: EnumDefault = {
  __signed: true,
  types: types,
}
