//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  x = 0,
  y = 1,
  z = 2,
}

export const ConfigGadgetConsoleOperationType: EnumDefault = {
  __signed: true,
  types: types,
}
