//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  WorldXZ = 0,
  ForwardTransLocal = 1,
}

export const ControlPartRotateBy: EnumDefault = {
  __signed: true,
  types: types,
}
