import { EnumDefault } from "."

enum types {
  CUSTOMGADGET_ROOT_NONE = 0,
  CUSTOMGADGET_ROOT_FURNITURE = 1,
  CUSTOMGADGET_ROOT_ACTIVITY_FLOWER = 2,
  CUSTOMGADGET_ROOT_ACTIVITY_SNOWMAN = 3,
  CUSTOMGADGET_ROOT_ACTIVITY_IRODORI_FLOWER = 4,
  CUSTOMGADGET_ROOT_ACTICITY_ISLAND_MOUNTAIN = 5,
  CUSTOMGADGET_ROOT_ACTIVITY_GRAVEN_INNOCENCE_CARVE = 6,
  CUSTOMGADGET_ROOT_ACTIVITY_VINTAGE_BOOTH = 7,
}

export const CustomGadgetRootType: EnumDefault = {
  __signed: true,
  types: types,
}
