import { EnumDefault } from "."

enum types {
  DUNGEN_ENTRY_TYPE_NONE = 0,
  DUNGEN_ENTRY_TYPE_AVATAR_EXP = 1,
  DUNGEN_ENTRY_TYPE_WEAPON_PROMOTE = 2,
  DUNGEN_ENTRY_TYPE_AVATAR_TALENT = 3,
  DUNGEN_ENTRY_TYPE_RELIQUARY = 4,
  DUNGEN_ENTRY_TYPE_SCOIN = 5,
  DUNGEON_ENTRY_TYPE_OBSCURAE = 6,
  DUNGEON_ENTRY_TYPE_NORMAL = 7,
  DUNGEON_ENTRY_TYPE_TRIAL = 8,
  DUNGEON_ENTRY_TYPE_EFFIGY = 9,
  DUNGEON_ENTRY_TYPE_FLEUR_FAIR = 10,
  DUNGEON_ENTRY_TYPE_CHANNELLER_SLAB_LOOP = 11,
  DUNGEON_ENTRY_TYPE_CHANNELLER_SLAB_ONE_OFF = 12,
  DUNGEON_ENTRY_TYPE_BLITZ_RUSH = 13,
  DUNGEON_ENTRY_TYPE_SUMO = 14,
  DUNGEON_ENTRY_TYPE_ACTIVITY = 15,
  DUNGEON_ENTRY_TYPE_HACHI = 16,
}

export const DungunEntryType: EnumDefault = {
  __signed: true,
  types: types,
}
