//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  DUNGEON_ROSTER_CYCLE_TYPE_NONE = 0,
  DUNGEON_ROSTER_CYCLE_TYPE_BY_ORDER = 1,
}

export const DungeonRosterCycleType: EnumDefault = {
  __signed: true,
  types: types,
}
