//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  None = 0,
  CharacterFrozen = 1,
  CharacterPetrifaction = 2,
  CharacterDie = 3,
  CharacterBurningToAshes = 4,
  CharacterDissolve = 5,
  GadgetFrozen = 6,
  GadgetPetrifaction = 7,
  GadgetDie = 8,
  AvatarDie = 9,
  MonsterEquipDie = 10,
  MonsterDie = 11,
  CharacterClip = 12,
  CharacterAlphaBlend = 13,
}

export const E_ShaderData: EnumDefault = {
  __signed: true,
  types: types,
}
