//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  None = 0,
  BeingHit = 1,
  ModifierAdd = 2,
  ModifierRemove = 3,
}

export const ElementReactionSourceType: EnumDefault = {
  __signed: true,
  types: types,
}
