//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  None = 0,
  Fire = 1,
  Water = 2,
  Grass = 3,
  Electric = 4,
  Ice = 5,
  Frozen = 6,
  Wind = 7,
  Rock = 8,
  AntiFire = 9,
  VehicleMuteIce = 10,
  COUNT = 11,
}

export const ElementType: EnumDefault = {
  __signed: true,
  types: types,
}
