//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  None = 0,
  SphericalFireworks = 1,
  PatternShapeFireworks = 2,
}

export const FireworksType: EnumDefault = {
  __signed: true,
  types: types,
}
