//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  Ground = 0,
  Wall = 1,
  Ceil = 2,
  StackObjPlane = 3,
  Door = 4,
  Chandelier = 5,
  Floor = 6,
  WallBody = 7,
  Carpet = 8,
  LegoRockery = 9,
  Stair = 10,
  NPC = 11,
  Animal = 12,
  Apartment = 13,
  FurnitureSuite = 14,
  Road = 15,
  Terrain = 16,
}

export const FurnitureDeploySurfaceType: EnumDefault = {
  __signed: true,
  types: types,
}
