//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  None = 0,
  MovieCanvas = 1,
}

export const GadgetCameraBoxUIActionType: EnumDefault = {
  __signed: true,
  types: types,
}
