//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  Mute = 0,
  Shake = 1,
  Light = 2,
  Heavy = 3,
  Air = 4,
}

export const HitLevel: EnumDefault = {
  __signed: true,
  types: types,
}
