//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  Invalid = 0,
  PlayerLevelGE = 1,
}

export const InvestigationMonsterMapMarkCreateConditionType: EnumDefault = {
  __signed: true,
  types: types,
}
