import { EnumDefault } from "."

enum types {
  IRODORI_CARD_TAG_NONE = 0,
  IRODORI_CARD_TAG_WATER = 1,
  IRODORI_CARD_TAG_FIRE = 2,
  IRODORI_CARD_TAG_ICE = 3,
  IRODORI_CARD_TAG_WIND = 4,
  IRODORI_CARD_TAG_ELECTRIC = 5,
  IRODORI_CARD_TAG_PHYSICS = 6,
  IRODORI_CARD_TAG_BOMB = 7,
  IRODORI_CARD_TAG_TRAP = 8,
  IRODORI_CARD_TAG_REPEL = 9,
  IRODORI_CARD_TAG_CHARACTER = 10,
  IRODORI_CARD_TAG_OTHER = 11,
}

export const IrodoriChessCardTag: EnumDefault = {
  __signed: true,
  types: types,
}
