import { EnumDefault } from "."

enum types {
  SITUATION_TYPE_NONE = 0,
  SITUATION_TYPE_COMMON_TRANSPORT = 1,
  SITUATION_TYPE_ENTER_QUEST_DUNGEON = 2,
  SITUATION_TYPE_ENTER_DAILY_DUNGEON = 3,
  SITUATION_TYPE_ENTER_TOWER = 4,
  SITUATION_TYPE_ENTER_ROOM = 5,
  SITUATION_TYPE_LOGIN = 6,
  SITUATION_TYPE_LOGOUT = 7,
  SITUATION_TYPE_REVIVE = 8,
  SITUATION_TYPE_ENTER_HOMEWORLD = 9,
  SITUATION_TYPE_ENTER_ISLAND = 10,
  SITUATION_TYPE_ENTER_GCG_NORMAL = 11,
  SITUATION_TYPE_ENTER_GCG_CATPUB = 12,
  SITUATION_TYPE_ENTER_GCG_PVE = 13,
  SITUATION_TYPE_ENTER_GCG_AI = 14,
  SITUATION_TYPE_ENTER_GCG_PVP = 15,
  SITUATION_TYPE_ENTER_GCG_FESTIVAL = 16,
}

export const LoadingTipsSituationType: EnumDefault = {
  __signed: true,
  types: types,
}
