//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  MAINQUEST_TAG_NONE = 0,
  MAINQUEST_TAG_GUIDE = 1,
  MAINQUEST_TAG_ACTIVITY = 2,
}

export const MainQuestTagType: EnumDefault = {
  __signed: true,
  types: types,
}
