//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  NONE = 0,
  EASY_TOUCH = 1,
  ACTION_PANEL = 2,
  TEAM_BTN = 3,
  MESSAGE_TIPS = 4,
  INTEE_PANEL = 5,
  AIM_CONTAINER = 6,
  SELF_RTT = 7,
  TOP_BTNS = 8,
  MAP_INFO = 9,
  CHAT_INFO = 10,
  MOVE = 11,
  GAME_INFO = 12,
  DIALOG = 13,
  MAIN_BTN = 14,
}

export const MainPageUIDisableType: EnumDefault = {
  __signed: true,
  types: types,
}
