//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  NONE = 0,
  MAP_MARK_NORMAL = 1,
  MAP_MARK_LOCAL_AVATAR = 2,
  MAP_MARK_LOCAL_SIGHT = 3,
  MAP_MARK_SOUTH = 4,
  MAP_MARK_MINI_OTHER = 5,
  MAP_MARK_CUSTOM = 6,
  OTHER = 7,
}

export const MarkViewType: EnumDefault = {
  __signed: true,
  types: types,
}
