//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  Default = 0,
  TransPoint = 1,
  Quest = 2,
  Custom = 3,
  LocalAvatar = 4,
  Companion = 5,
  Monster = 6,
  NearHint = 8,
  ScenePoint = 9,
  Task = 10,
  Boss = 11,
  Talk = 12,
  PacketAnchor = 13,
  Widget = 14,
  FlightChallenge = 15,
  Hunting = 16,
  Routine = 17,
  ActivitySearchRegion = 18,
  GalleryChallenge = 19,
  HomeworldDynamic = 20,
  SignalPoint = 21,
  Vehicle = 22,
  HomeworldFurnitureSuite = 23,
  Activity = 24,
  HomeworldFarmField = 25,
  Offering = 26,
  QuestAcception = 27,
}

export const MarkType: EnumDefault = {
  __signed: true,
  types: types,
}
