//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  MATCH_SUB_TYPE_NONE = 0,
  MATCH_SUB_TYPE_HIDE = 1,
  MATCH_SUB_TYPE_BOUNCE_CONJURING = 2,
  MATCH_SUB_TYPE_ISLAND_PARTY = 3,
}

export const MatchSubType: EnumDefault = {
  __signed: true,
  types: types,
}
