//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  TAG_NONE = 0,
  TAG_FIRE = 1,
  TAG_TEST_ONE = 2,
  TAG_TEST_TWO = 3,
  TAG_SCOIN = 4,
  TAG_AVATAR_EXP = 5,
  TAG_WEAPON_EXP = 6,
  TAG_AVATAR_PROMOTE = 7,
  TAG_WEAPON_PROMOTE = 8,
  TAG_SKILL_BOOK = 9,
}

export const MiracleTag: EnumDefault = {
  __signed: true,
  types: types,
}
