//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  MOONFIN_TRIAL_ACTIVITY_LEVEL_TYPE_QUEST = 0,
  MOONFIN_TRIAL_ACTIVITY_LEVEL_TYPE_CHALLENGE_TOTAL = 1,
  MOONFIN_TRIAL_ACTIVITY_LEVEL_TYPE_CHALLENGE_SPECIFIC = 2,
  MOONFIN_TRIAL_ACTIVITY_LEVEL_TYPE_CHALLENGE_CONTINUOUS = 3,
  MOONFIN_TRIAL_ACTIVITY_LEVEL_TYPE_SPECIAL_FISH = 4,
}

export const MoonfinTrialActivityLevelType: EnumDefault = {
  __signed: true,
  types: types,
}
