//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  NONE = 0,
  WALK = 1,
  RUN = 2,
  NONEACCURATE = 3,
  DIRECT = 4,
}

export const MoveToType: EnumDefault = {
  __signed: true,
  types: types,
}
