//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  NONE = 0,
  AVATAR_MALE = 1,
  AVATAR_LADY = 2,
  AVATAR_BOY = 3,
  AVATAR_GIRL = 4,
  AVATAR_LOLI = 5,
  AVATAR_PAIMON = 6,
  NPC_MALE = 7,
  NPC_FEMALE = 8,
  NPC_MUSCLEMAN = 9,
  NPC_ELDER = 10,
  NPC_CHILD = 11,
  Barbara = 12,
  Bennett = 13,
  Chongyun = 14,
  Noel = 15,
  Diona = 16,
  Sayu = 17,
  Tohma = 18,
  Beidou = 19,
  Gorou = 20,
  Ningguang = 21,
}

export const NPCBodyType: EnumDefault = {
  __signed: true,
  types: types,
}
