//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  None = 0,
  HP = 1,
  ExpGain = 2,
  ChestOpen = 3,
  QuestFinish = 4,
  PickItem = 5,
  HPUp = 6,
  HPDown = 7,
  EnergyDonwBySkill = 8,
  SkillReady = 9,
}

export const OnEventType: EnumDefault = {
  __signed: true,
  types: types,
}
