//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  QTE_STEP_BUTTON_INPUT_JUMP = 0,
  QTE_STEP_BUTTON_INPUT_LEFT_MOVE = 1,
}

export const QTEStepButtonInputType: EnumDefault = {
  __signed: true,
  types: types,
}
