//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  QUEST_GUIDE_STYLE_NONE = 0,
  QUEST_GUIDE_STYLE_START = 1,
  QUEST_GUIDE_STYLE_TARGET = 2,
  QUEST_GUIDE_STYLE_FINISH = 3,
  QUEST_GUIDE_STYLE_POINT = 4,
}

export const QuestGuideStyle: EnumDefault = {
  __signed: true,
  types: types,
}
