//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  QUEST_GUIDE_LAYER_NONE = 0,
  QUEST_GUIDE_LAYER_UI = 1,
  QUEST_GUIDE_LAYER_SCENE = 2,
}

export const QuestGuideLayer: EnumDefault = {
  __signed: true,
  types: types,
}
