//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  REGION_SEARCH_TYPE_NONE = 0,
  REGION_SEARCH_TYPE_ACTIVITY = 1,
}

export const RegionSearchType: EnumDefault = {
  __signed: true,
  types: types,
}
