//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  MichiaeMatsuriDarkPressure = 2500,
  MichiaeMatsuriCrystalEnergy = 2501,
  LightStoneEnergy = 2600,
}

export const RegionalPlayVarType: EnumDefault = {
  __signed: true,
  types: types,
}
