//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  ByAttacker = 0,
  ByHitDirection = 1,
  ByTangent = 2,
  ByOriginOwner = 3,
  ByHitDirectionInverse = 4,
  ByAttackerForward = 5,
  ByAttackerInverse = 6,
}

export const RetreatType: EnumDefault = {
  __signed: true,
  types: types,
}
