//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  METHOD_DAY_PROBABILITY = 0,
  METHOD_DAY_ACCUMULATION = 1,
}

export const SalesmanSpecialRewardObtainMethod: EnumDefault = {
  __signed: true,
  types: types,
}
