//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  Any = 0,
  InSet = 1,
  Except = 2,
}

export const StateAudioEventUsage: EnumDefault = {
  __signed: true,
  types: types,
}
