//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  TIME = 0,
  PARAM = 1,
}

export const SummerTimeV2BoatConditionType: EnumDefault = {
  __signed: true,
  types: types,
}
