//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  TALK_NORMAL_QUEST = 0,
  TALK_BLOSSOM = 1,
  TALK_ACTIVITY = 2,
  TALK_COOP = 3,
  TALK_GADGET = 4,
}

export const TalkLoadType: EnumDefault = {
  __signed: true,
  types: types,
}
