import { EnumDefault } from "."

enum types {
  TALK_EXEC_NONE = 0,
  TALK_EXEC_SET_GADGET_STATE = 1,
  TALK_EXEC_SET_GAME_TIME = 2,
  TALK_EXEC_NOTIFY_GROUP_LUA = 3,
  TALK_EXEC_SET_DAILY_TASK_VAR = 4,
  TALK_EXEC_INC_DAILY_TASK_VAR = 5,
  TALK_EXEC_DEC_DAILY_TASK_VAR = 6,
  TALK_EXEC_SET_QUEST_VAR = 7,
  TALK_EXEC_INC_QUEST_VAR = 8,
  TALK_EXEC_DEC_QUEST_VAR = 9,
  TALK_EXEC_SET_QUEST_GLOBAL_VAR = 10,
  TALK_EXEC_INC_QUEST_GLOBAL_VAR = 11,
  TALK_EXEC_DEC_QUEST_GLOBAL_VAR = 12,
  TALK_EXEC_TRANS_SCENE_DUMMY_POINT = 13,
  TALK_EXEC_SAVE_TALK_ID = 14,
}

export const TalkExecType: EnumDefault = {
  __signed: true,
  types: types,
}
