//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  DEFAULT = 0,
  IOS = 1,
  PC = 2,
  ANDROID = 3,
  PS4 = 4,
  SWITCH = 5,
  PS5 = 6,
}

export const TextMapPlatformType: EnumDefault = {
  __signed: true,
  types: types,
}
