//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  None = 0,
  NormalAttack = 1,
  Skill = 2,
  UltimateSkill = 3,
  Count = 4,
}

export const UseSkillType: EnumDefault = {
  __signed: true,
  types: types,
}
