import { EnumDefault } from "."

enum types {
  VINTAGE_MARKET_EFFECT_NONE = 0,
  VINTAGE_MARKET_EFFECT_ATTR_ADD_FIXED = 1,
  VINTAGE_MARKET_EFFECT_ATTR_SUB_FIXED = 2,
  VINTAGE_MARKET_EFFECT_AIM_ATTR_ADD_FIXED = 3,
  VINTAGE_MARKET_EFFECT_AIM_ATTR_SUB_FIXED = 4,
  VINTAGE_MARKET_EFFECT_ATTR_ADD_PERCENT = 5,
  VINTAGE_MARKET_EFFECT_FIXED_INCOME_WITH_ENV = 6,
  VINTAGE_MARKET_EFFECT_PERCENT_INCOME_WITH_ENV = 7,
  VINTAGE_MARKET_EFFECT_ADD_FIXED_ATTR_WITH_ENV = 8,
  VINTAGE_MARKET_EFFECT_ADD_PERCENT_ATTR_WITH_ENV = 9,
  VINTAGE_MARKET_EFFECT_REWARD_FACTOR = 10,
  VINTAGE_MARKET_EFFECT_FIXED_INCOME_BY_TOTAL_INCOME = 11,
  VINTAGE_MARKET_EFFECT_PERCENT_INCOME_BY_TOTAL_INCOME = 12,
  VINTAGE_MARKET_EFFECT_PROB_RETURN_COST_WHEN_ATTR_GE_AIM = 13,
  VINTAGE_MARKET_EFFECT_PERCENT_INCOME_WHEN_ATTR_GE_AIM = 14,
}

export const VintageMarketEffectType: EnumDefault = {
  __signed: true,
  types: types,
}
