//Auto Generated by ConfigParser

import { EnumDefault } from "."

enum types {
  ActionPanel = 1,
  FlyAttach = 2,
}

export const WidgetOccupyTag: EnumDefault = {
  __signed: true,
  types: types,
}
