//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActCameraShake: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    cameraShake: "ConfigCameraShake",
    born: "ConfigBornType",
  },
}
