//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActCameraRadialBlur: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    cameraRadialBlur: "ConfigCameraRadialBlur",
  },
}
