//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AddRegionalPlayVarValue: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    varType: "RegionalPlayVarType",
    addValue: "float",
  },
}
