//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AnimatorTrigger: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    id: "vuint",
    isSet: "bool",
  },
}
