//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AnimatorRecordState: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    shortNameHash: "vuint",
    stateLength: "float",
    normalizedTime: "float",
  },
}
