//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ApplyLevelModifier: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    modifierName: "string",
  },
}
