//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AttachBulletAimPoint: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    bulletAimPoint: "string",
  },
}
