//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AudioUiSupport: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    comboRtpcKey: "ConfigWwiseString",
    countdown: "float",
  },
}
