//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AudioSettingSlider_PostVoiceItem: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    voiceTriggerIdentity: "VoiceTriggerIdentity",
    repeatCount: "vuint",
  },
}
