//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AudioSettingSlider_PostVoice: ConfigDefault = {
  attribute: [],
  baseClass: "AudioSettingSlider",
  Fields: {
    changeVoiceArray: "AudioSettingSlider_PostVoiceItem[]",
  },
}
