//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AudioSettingSlider: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    rtpc: "ConfigWwiseString",
    textMap: "string",
    minValue: "vuint",
    maxValue: "vuint",
    eachValues: "float[]",
  },
}
