//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AudioStateOp: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    group: "ConfigWwiseString",
    value: "ConfigWwiseString",
  },
}
