//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AudioImpactOverrideEvent: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    entityId: "vuint",
    impactEvent: "AudioOneTimeEvent",
  },
}
