//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AudioPlatformSetting: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    audioAPIDefaultOpenSL_ESRequirements: "AudioRequirement[][]",
  },
}
