//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AudioSettingSlider_PostEvent: ConfigDefault = {
  attribute: [],
  baseClass: "AudioSettingSlider",
  Fields: {
    changeEvent: "ConfigWwiseString",
  },
}
