//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AudioUiEquip: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    equipOnEvent: "ConfigWwiseString",
  },
}
