//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AvatarCameraParam: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    cameraParam: "ConfigStateCameraParam",
  },
}
