//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AvatarSpeechEquipObtain: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    quality: "vint",
    eventName: "ConfigWwiseString",
  },
}
