//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AvatarExitViewBias: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    lerpDuration: "float",
    lerpRadius: "float",
  },
}
