//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BillboardMarkMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    iconName: "string",
    showDistance: "float",
  },
}
