//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BillboardFixedMarkMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    prefabName: "string",
    onlyShowInElementView: "bool",
  },
}
