//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BowDrawTime: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    bowDrawStartNormTime: "float",
    bowDrawEndNormTime: "float",
    bowStringOverridePoint: "string",
  },
}
