//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BusChannelConfig: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    bus: "ConfigWwiseString",
    channelMask: "vuint",
  },
}
