//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByAttackType: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    attackType: "AttackType",
  },
}
