//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByAvatarIsHost: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    isHost: "bool",
  },
}
