//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByCurTeamElementTypeSort: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    number: "vuint",
    logic: "RelationalOperator",
  },
}
