//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByCurrentSceneTypes: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    SceneTypes: "SceneType[]",
  },
}
