//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByDieStateFlag: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    dieStateFlag: "DieStateFlag",
  },
}
