//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByElementReactionType: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    reactionType: "ElementReactionType",
  },
}
