//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByEntityAppearVisionType: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    visionType: "EntityAppearVisionType",
  },
}
