//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByFindBlinkPointSuccess: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    findPointSuccess: "bool",
  },
}
