//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByHasFeatureTag: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    featureTagIDs: "vuint[]",
  },
}
