//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByHasElement: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    element: "ElementType",
  },
}
