//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByHitEnBreak: ConfigDefault = {
  attribute: [],
  baseClass: "RelationalOperationPredicate",
  Fields: {
    enBreak: "DynamicFloat",
  },
}
