//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByHitBoxType: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    hitBoxType: "HitBoxType",
  },
}
