//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByHitBoxName: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    hitBoxNames: "string[]",
  },
}
