//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByItemNumber: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    itemId: "vuint",
    itemNum: "vuint",
  },
}
