//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByNot: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    predicates: "ConfigAbilityPredicate[]",
  },
}
