//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByPlayerClimateType: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    climateType: "JsonClimateType",
  },
}
