//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BySceneSurfaceType: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    filters: "SceneSurfaceType[]",
    include: "bool",
    offset: "Vector",
  },
}
