//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BySummonTagValue: ConfigDefault = {
  attribute: [],
  baseClass: "RelationalOperationPredicate",
  Fields: {
    summonTag: "vuint",
    value: "DynamicInt",
  },
}
