//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByTargetType: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    targetType: "AbilityTargetting",
    isTarget: "bool",
  },
}
