//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByTargetWeatherName: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    weatherName: "string",
  },
}
