//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByTargetOverrideMapValue: ConfigDefault = {
  attribute: [],
  baseClass: "RelationalOperationPredicate",
  Fields: {
    targetAbilityName: "string",
    targetKey: "string",
    targetValue: "DynamicFloat",
  },
}
