//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByTargetForwardAndSelfPosition: ConfigDefault = {
  attribute: [],
  baseClass: "RelationalOperationPredicate",
  Fields: {
    value: "DynamicFloat",
    isXZ: "bool",
  },
}
