//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ByUnlockTalentParam: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityPredicate",
  Fields: {
    talentParam: "string",
  },
}
