//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CalcDvalinS04RebornPoint: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    enable: "bool",
  },
}
