//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CameraBlurMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    cameraRadialBlur: "ConfigCameraRadialBlur",
  },
}
