//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CameraLockMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    transName: "string",
    cfgPath: "string",
  },
}
