//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ChangeUGCRayTag: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    rayTag: "vuint",
  },
}
