//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ChangePropTypeValueMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    propType: "string",
    energyCostDelta: "DynamicFloat",
  },
}
