//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ChangeFieldMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    type: "ChangeFieldType",
    targetRadius: "float",
    time: "float",
  },
}
