//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ChangeColliderSurface: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    transformName: "string",
    surfaceType: "SceneSurfaceType",
  },
}
