//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ChangePlayMode: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    toPlayMode: "PlayModeType",
    authorityOnly: "bool",
  },
}
