//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ChangeTag: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    isAdd: "bool",
    tag: "string",
  },
}
