//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicDoubleNoLessThanCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicDoubleCondition",
  Fields: {},
}
