//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideShowPage: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuideAction",
  Fields: {
    contextName: "string",
    enable: "bool",
  },
}
