//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigHomeworldFurnitureUnit: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    furnitureID: "vuint",
    position: "Vector",
    rotation: "Vector",
    parentIndex: "vint",
  },
}
