//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAudioArea2DInfo: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    leaveReverbDelay: "float",
    enterReverbStates: "AudioStateOp[]",
    leaveReverbStates: "AudioStateOp[]",
  },
}
