//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIOrderSetting: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    master: "ConfigAIOrderMasterSetting",
    servant: "ConfigAIOrderServantSetting",
    commandSetting: "ConfigAICommandSetting",
  },
}
