//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWidgetAddBuff: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseWidgetToy",
  Fields: {
    buffId: "vuint",
  },
}
