//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetPattern: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    collision: "ConfigCollision",
    colliderCheckOnInit: "bool",
  },
}
