//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIFindBackSetting: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAITacticBaseSetting",
  Fields: {
    defaultSetting: "ConfigAIFindBackData",
    specification: "map<vint,ConfigAIFindBackData>",
  },
}
