//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigPerfNumberArrayItemOverrideInfo: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigPerfItemOverrideInfoBase",
  Fields: {
    overrideValue: "float[]",
  },
}
