//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIMixinSetBool: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    boolID: "string",
    value: "bool",
  },
}
