//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigShadowQualitySetting: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    shadowDistance: "vint",
    shadowResolution: "ConfigShadowResolution",
    shadowCascadeSplitCount: "vint",
    perObjShadowQuality: "vint",
    shadowBlend: "bool",
    PerObjectPCF: "bool",
    enableDynamicShadow: "bool",
    enablePcss: "bool",
    enableDistantShadow: "bool",
  },
}
