//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMainPageDisableInfo: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    uiDisableList: "MainPageUIDisableType[]",
    enabledInputEventList: "InputEventType[]",
  },
}
