//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGlobalToken: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    actionTokenGroup: "string",
  },
}
