//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigPerfItemOptionArrayInfoBase: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    requirementArray: "ConfigGraphicsRequirement[]",
  },
}
