//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBoolForPlatforms: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    ps4: "bool",
    android: "bool",
    ios: "bool",
    pc: "bool",
    editor: "bool",
  },
}
