//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicParameterizedStimulusHandler: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicStimulusHandler",
  Fields: {},
}
