//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigSceneMeta: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    blockInfo: "ConfigLevelBlockMeta[]",
    navmeshPolygonDataPathHashSuffix: "vuint",
    navmeshPolygonDataPathHashPre: "byte",
  },
}
