//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWidgetClientDetector: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseWidget",
  Fields: {
    gadgetId: "vuint",
    allowCityId: "vuint",
    hintGroup: "vuint",
    distanceToAvatar: "float",
    height: "float",
  },
}
