//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigPerfGradeItemOverrideInfo: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigPerfItemOverrideInfoBase",
  Fields: {
    overrideValue: "vint",
  },
}
