import { ConfigDefault } from "../"

export const ConfigAvatarSpeech: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    suitableEquipObtain: "AvatarSpeechEquipObtain[]",
    unsuitableEquipObtain: "AvatarSpeechEquipObtain[]",
    eventCommonPrefix: "string",
    externalVoiceEvent: "ConfigWwiseString",
    personSwitchKey: "ConfigWwiseString",
    positioningSwitchKey: "ConfigWwiseString",
    initialDelayRTPC: "ConfigWwiseString",
    personSwitchValueMap: "map<string,string>",
    positioningSwitchValueMap: "map<string,string>",
    externalSoundNames: "VoiceSound[]",
    defaultNarrationInterval: "float",
    defaultNarrationDuration: "float",
    defaultNarrationMaxDuration: "float",
    gachaVoiceTriggerParam: "vuint",
    joinTeamVoiceTriggerParam: "vuint",
    fetterVoiceTriggerMap: "map<vuint,VoiceTriggerIdentity>",
    teammateLowHPVo_hpRatio: "float",
    teammateLowHPVo_cooldown: "vuint",
    teammateLowHPVo_voTrigger: "VoiceTriggerIdentity",
    teammateLowHPVo_distance: "float",
    teammateLowHPVo_hpDescRatio: "float",
    teammateLowHPVo_distanceMap: "map<vuint,float>",
    localPlayerLowHPVo_hpRatio: "float",
    localPlayerLowHPVo_cooldown: "vuint",
    localPlayerLowHPVo_voTrigger: "VoiceTriggerIdentity",
    promotionVoiceTriggerMap: "map<vuint,VoiceTriggerIdentity>",
    openChestVoTrigger: "VoiceTriggerIdentity",
    voiceBlackList: "string[]",
  },
}
