//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigEntityBanData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    entityBanMap: "map<string,ConfigEntityBlackGrp[]>",
  },
}
