//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBattleFervorUpdateTrigger_ByElementArt: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBattleFervorUpdateTrigger",
  Fields: {
    cd: "float",
  },
}
