//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigDirectionByGlobalValue: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBornDirectionType",
  Fields: {
    directionKey: "string",
  },
}
