//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCameraShakeExt: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    infinity: "bool",
    baseOnCamera: "bool",
    afterShake: "bool",
    baseCycle: "float",
    cycleDamping: "float",
    rangeAttenuation: "float",
  },
}
