//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWidgetLightStone: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseWidgetToy",
  Fields: {
    levelEnergyLimitArray: "vuint[]",
    levelCdGroupIdArray: "vuint[]",
    quickUseOpenLevel: "vuint",
    skyCrystalDetectorOpenLevel: "vuint",
    energyType: "RegionalPlayVarType",
    gadgetChainId: "vuint",
    quickUseCostEnergy: "vuint",
    abilityGroupName: "string",
    triggerAbilityName: "string",
    isTeam: "bool",
    hintRadius: "vuint",
    nearbyRadius: "vuint",
    gridSearchRange: "vuint",
    successGadgetId: "vuint",
    failedGadgetId: "vuint",
    gatherPointType: "vuint",
    hintGroup: "vuint",
    effectLastTime: "vuint",
    distanceToAvatar: "float",
    height: "float",
  },
}
