//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigDefaultAbilities: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    monterEliteAbilityName: "string",
    nonHumanoidMoveAbilities: "string[]",
    levelDefaultAbilities: "string[]",
    levelElementAbilities: "string[]",
    levelItemAbilities: "string[]",
    levelSBuffAbilities: "string[]",
    dungeonAbilities: "string[]",
    defaultTeamAbilities: "string[]",
    defaultMPLevelAbilities: "string[]",
    defaultAvatarAbilities: "string[]",
  },
}
