//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigEffectItanoCircusBullet: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMultiBullet",
  Fields: {
    effectPattern: "string",
  },
}
