//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigEntityAudio: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    animAudio: "ConfigAnimationAudio",
    initEvent: "ConfigWwiseString",
    enableEvent: "ConfigWwiseString",
    disableEvent: "ConfigWwiseString",
    destroyEvent: "ConfigWwiseString",
  },
}
