//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideHideandSeekSkillCategoryCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuidePageCheckBaseCondition",
  Fields: {
    index: "vint",
    isSelect: "bool",
  },
}
