//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAbilityPath: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    abilityPaths: "map<string,string[]>",
  },
}
