//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCameraSplineInterAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseInterAction",
  Fields: {
    cameraPath: "ConfigCameraSplineCameraPath",
    targetPath: "ConfigCameraSplineTargetPath",
    targetDuration: "float",
  },
}
