//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGlobalCollision: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    highSpdThreshold: "float",
  },
}
