//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLevelMeta: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    sceneMetaDic: "map<vuint,ConfigSceneMeta>",
  },
}
