//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCutsceneIndex: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    normal: "ConfigCutsceneContext",
    platform: "map<vint,ConfigCutsceneContext>",
  },
}
