//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigParabolaBulletMoveCorrection: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMoveCorrection",
  Fields: {
    deviation: "float",
    fixAngleOfVer: "float",
    minSpeed: "float",
    maxSpeed: "float",
  },
}
