//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideProjectionGameFinishCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuideCondition",
  Fields: {
    finishType: "ProjectionGameGuideFinishType",
    param: "float",
  },
}
