//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigNPCMove: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAnimatorMove",
  Fields: {
    waterCheck: "bool",
  },
}
