//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicStringCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicParameterCondition",
  Fields: {
    value: "string",
  },
}
