//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLogSetting: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    sendEngineLogToServer: "bool",
  },
}
