//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicStringContainmentCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicStringCondition",
  Fields: {},
}
