//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicGameCamera: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    cameraConfigList: "ConfigMusicCamera[]",
  },
}
