//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigInterGrpId: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    index: "vuint",
    grpId: "vuint",
    nextGrpId: "vuint",
  },
}
