//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWidgetToyWaterSprite: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseWidgetToy",
  Fields: {
    abilityGroupName: "string",
    abilityTriggerName: "string",
    abilityTriggerNameSecond: "string",
  },
}
