//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBowData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    bowRatioName: "string",
    bowStringLoosePoint: "Vector",
    bowStringMaxLen: "float",
  },
}
