//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAudioAvatarMove: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    flyDirectionRtpcKey: "ConfigWwiseString",
    flyDirectionRtpcFront: "float",
    flyDirectionRtpcSide: "float",
    flyDirectionRtpcBack: "float",
    flyDirectionRtpcDrop: "float",
    lastFrameSpeedInAirRtpcKey: "ConfigWwiseString",
    eventFallInWater: "ConfigWwiseString",
    altitudeRtpcKey: "ConfigWwiseString",
    slopeRtpcKey: "ConfigWwiseString",
    flyTurnEvent: "ConfigWwiseString",
    flyTurnEventInterval: "float",
    flySpeedRtpcKey: "ConfigWwiseString",
    airflowSpeedGain: "float",
    airflowGainFadeLength: "float",
    climbVerticalScalerRtpcKey: "ConfigWwiseString",
    climbVerticalScalerAnimatorKey: "ConfigWwiseString",
    cameraAngleXRtpcKey: "ConfigWwiseString",
    cameraAngleYRtpcKey: "ConfigWwiseString",
    enterSpeedupFieldEvent: "ConfigWwiseString",
    fallOnWaterRtpcKey: "ConfigWwiseString",
  },
}
