//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetStateFireEffect: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGadgetStateAction",
  Fields: {
    rootName: "string",
    effectPattern: "string",
  },
}
