//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLocalEntity: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigScenePoint",
  Fields: {
    checkDist: "float",
    withGO: "bool",
  },
}
