//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigPhotographCheck: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    allJudgeNodes: "map<vuint,ConfigJudgeNodeBase>",
  },
}
