//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicStringAbsenceStimulusHandler: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicStringMultiValueStimulusHandler",
  Fields: {},
}
