//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigPerfCombinedItem: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigPerfItemBase",
  Fields: {
    itemOptionMap: "map<string,ConfigPerfCombineItemOptionArrayInfo>",
  },
}
