//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigPerfBoolItemOptionArrayInfo: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigPerfItemOptionArrayInfoBase",
  Fields: {
    itemOptionArray: "bool[]",
  },
}
