//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWindSeed: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    athuorityRadius: "float",
  },
}
