//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBladeElementFx: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    slash: "string",
    colorA: "string",
    colorB: "string",
  },
}
