//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAISpacialWanderConeWeightData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    normalAreaWeight: "vuint[]",
    edgeAreaWeight: "vuint[]",
  },
}
