//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAITSAbilityGlobalValueSetting: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAIThreatScoreBaseSetting",
  Fields: {
    caredGlobalValueName: "string",
  },
}
