//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigSummonTag: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    summonTag: "vuint",
    name: "string",
    maxNum: "vint",
    copyOwnerThreatList: "bool",
    useOwnerDefendArea: "bool",
  },
}
