//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigResourceCollection: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    resourceCollectionMap: "map<vuint,ConfigResourceCollectionContent>",
  },
}
