//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigQTEButtonCountDownValueCond: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigQTEStepBaseCond",
  Fields: {
    orderType: "OrderingType",
    value: "float",
  },
}
