//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBornByStormLightning: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBornType",
  Fields: {
    hitHeightRatio: "float",
    selectRange: "float",
    maxOffsetLen: "float",
    lightningHitOrNotRatio: "float",
  },
}
