//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetStateSetAnimTrigger: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGadgetStateAction",
  Fields: {
    triggerID: "string",
  },
}
