//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCloseGPUCullingInterAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseInterAction",
  Fields: {},
}
