//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigRecordRagdollParameters: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    prefabHash: "vuint",
    velocityOnRoot: "Vector",
    explosionForce: "Vector",
  },
}
