import { ConfigDefault } from ".."

export const ConfigGlobalCombat: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    hitData: "ConfigGlobalHit",
    collisionData: "ConfigGlobalCollision",
    aiData: "ConfigGlobalAI",
    moveData: "ConfigGlobalMove",
    defaultAvatarHitBucketSetting: "ConfigAvatarHitBucketSetting",
    elementBladeData: "map<string,ConfigBladeElementFx>",
    fireGrassAirflowData: "ConfigFireGrassAirflowField",
    miscs: "ConfigGloablMiscs",
    defaultAbilities: "ConfigDefaultAbilities",
    elemReactDamage: "map<string,map<string,float>>",
    elemAmplifyDamage: "map<string,map<string,float>>",
    elemPrority: "ElementType[]",
    shakeOff: "ConfigGlobalShakeOff",
    elementShield: "ConfigElementShield",
    eliteShield: "ConfigEliteShield",
    globalSwitch: "ConfigGlobalSwitch",
    lockTarget: "ConfigGlobalLockTarget",
    elemUI: "ConfigElementUI",
    rejectElementReaction: "map<AbilityState,ElementReactionType[]>",
    logSetting: "ConfigLogSetting",
    attackAttenuation: "map<string,ConfigAttackAttenuation>",
    gadgetCreationLimits: "ConfigGadgetCreationLimit[]",
    luaSafetySwitch: "ConfigLuaSafetyCheckSwitch",
    tempComponentBudget: "map<vint,float>",
    globalInteraction: "ConfigGlobalInteraction",
    lampOffset: "Vector[]",
    abilityStateTriggerAbilities: "map<AbilityState,string>",
    dither: "ConfigGlobalDither",
    elementDecrateGroup: "map<string,ConfigElementDecrate[]>",
    sliceFrameWatch: "ConfigSliceFrameWatch",
    ik: "ConfigIK",
    avatarEquipSizeDatas: "map<vint,EquipSizeData[]>",
    manekinEquipSizeDatas: "map<vint,EquipSizeData[]>",
    bigWorldEnvironmentDamageClamp: "ConfigBigWorldEnvironmentDamageClamp",
    tdPlay: "ConfigTDPlay",
    gameAnimSafeType: "ConfigSafeTypeReportData",
    elementConvertToChargeBarValueMixinItemGroup: "map<string,ElementConvertToChargeBarValueMixinItem[]>",
    chargeBarMixinGlobalValueKey: "string",
    elementReactionCoefficients: "ConfigElementReactionCoefficients",
    battleFervorFormula: "ConfigBattleFervorFormula",
    combatTemplate: "map<string,ConfigCombat>",
    combatAntiCheatAttackTagWhiteList: "string[]",
    mixinCheckModifierWhiteList: "ConfigMixinCheckModifierWhiteList",
    footprintZones: "map<FootprintZoneType,ConfigFootprintZoneEffect[]>",
    mushroomConfigIdlist: "vuint[]",
    overgrowEnvironmentLimit: "ConfigOvergrowEnvironmentLimit",
    globalValueList: "GlobalValueRegister[]",
    attacktagToElementreactionDictionary: "map<string,ElementReactionType>",
  },
}
