//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAITSTargetDistanceSetting: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAIThreatScoreBaseSetting",
  Fields: {},
}
