//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCrystal: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    elementType: "ElementType",
    gainSpeed: "vuint",
    drainSpeed: "vuint",
    resonateLevels: "vuint[]",
    burstResonate: "vuint",
    burstSkill: "string",
    burstTime: "vuint",
    respawnTime: "vuint",
  },
}
