//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetUIExtraItem: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGadgetUIBase",
  Fields: {
    extraId: "vint",
  },
}
