//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWidgetAttachAvatar: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseWidget",
  Fields: {
    useGadgetId: "vuint",
  },
}
