//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBulletMoveAngleRotating: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBulletMoveAngle",
  Fields: {
    angularVelocity: "Vector",
  },
}
