//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetCameraBox: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    configName: "string",
    enterRadius: "float",
    exitRadius: "float",
    uiAction: "GadgetCameraBoxUIActionType",
  },
}
