//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigUITriggerInterAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseInterAction",
  Fields: {
    contextName: "string",
    param: "string",
  },
}
