//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAudioPositionedEmitterOp: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAudioPositionedOp",
  Fields: {},
}
