//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigResonanceCutSceneMap: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    cutsceneMap: "map<ElementType,ConfigResonanceCutScene>",
  },
}
