//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigSimpleAttackPattern: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseAttackPattern",
  Fields: {
    useCustomShape: "bool",
  },
}
