//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigEntityReuse: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    configId: "vuint",
    destroyTime: "float",
    maxEntityCount: "vuint",
  },
}
