//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigConstForceField: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigForceField",
  Fields: {
    velocity: "float",
  },
}
