//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLuaSafetyCheckSwitch: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    tickWorld: "bool",
    tickWorldCD: "vuint",
    tickChest: "bool",
    tickMonster: "bool",
  },
}
