//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicInt32GreaterThanCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicInt32Condition",
  Fields: {},
}
