//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigEffectWithThreshold: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    threshold: "float",
    effectName: "string",
  },
}
