//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIReactActionPointData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    reactList: "ConfigAIPickActionPointCriteria[]",
  },
}
