//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigVehicleSeat: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    attachTo: "string",
    optionID: "vuint",
    rotate: "Vector",
    offVehicleUpDist: "float",
  },
}
