//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAbilityPropertyEntry: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    Type: "PropertyType",
    DefaultValue: "float",
    Ceiling: "float",
    Floor: "float",
    Stacking: "StackMethod",
    Succeed: "bool",
    UseTag: "bool",
    LimitedTagCeiling: "float",
    LimitedTagFloor: "float",
  },
}
