//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBaseStateLayer: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    layerIndex: "vint",
    layerIndexName: "string",
  },
}
