//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideMechanicusCurseCardCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuideCondition",
  Fields: {
    hasCurse: "bool",
  },
}
