//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicUIntAbsenceStimulusHandler: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicUIntMultiValueStimulusHandler",
  Fields: {},
}
