//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigElementReactionCoefficients: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    coefficientOverdose: "float",
  },
}
