//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAirflowField: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigConstForceField",
  Fields: {
    scale: "float",
    stayEffect: "string",
    enterEffect: "string",
    autoFly: "bool",
    forceHor: "bool",
  },
}
