//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicTransitions: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    shifters: "ConfigMusicShifter[]",
  },
}
