//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigDirectionByGroundNormal: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBornDirectionType",
  Fields: {},
}
