//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAbilitySystem: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    shouldPreActive: "bool",
    tasks: "ConfigAbilityTask[]",
  },
}
