//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLevelMonsterAIPatrol: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    aiPatrolGroupId: "vuint",
    aiPatrolIsLeader: "bool",
    aiPatrolOffset: "Point2D",
  },
}
