//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicNegativeCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicCondition",
  Fields: {
    innerId: "vint",
  },
}
