//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWidgetToyAdeptiAbode: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigWidgetToyCreateGadgetBase",
  Fields: {
    abilityName: "string",
    effectLastTime: "float",
  },
}
