//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAttackAttenuation: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    resetCycle: "float",
    durabilitySequence: "float[]",
    enbreakSequence: "float[]",
    damageSequence: "float[]",
  },
}
