//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWorldAreaLayout: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    level1Areas: "ConfigLevel1WorldArea[]",
  },
}
