//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigDirectionByRefraction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBornDirectionType",
  Fields: {
    validAngleRange: "float",
  },
}
