//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigJudgeGroupEntityDirectionHasBlock: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigJudgeNodeBase",
  Fields: {
    groupEntityList: "ConfigJudgeGroupEntity[]",
    detectDistance: "float",
  },
}
