//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBattleFervorUpdateTrigger_ByElementBurst: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBattleFervorUpdateTrigger",
  Fields: {
    cd: "float",
  },
}
