//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIMove: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    enable: "bool",
    moveCategory: "MoveCategoryAI",
    useNavMesh: "bool",
    navMeshAgentName: "string",
    almostReachedDistanceWalk: "float",
    almostReachedDistanceRun: "float",
    snakelikeMoveSetting: "ConfigAISnakelikeMove",
  },
}
