//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCharacterRendering: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    overrideLightDir: "bool",
    overrideLightEulerAngle: "Vector",
  },
}
