//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetSpecialCamera: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigSpecialCamera",
  Fields: {
    enterAngle: "float",
    exitAngle: "float",
  },
}
