//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigRecordActorBase: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    pos: "Vector",
    rot: "Vector",
    scale: "Vector",
    serialID: "vuint",
  },
}
