//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigQTEStepCondGroup: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    condCombType: "LogicType",
    stepCondList: "ConfigQTEStepBaseCond[]",
  },
}
