//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigPlayUIEffectAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseInterAction",
  Fields: {
    uiCameraEffectPath: "string",
    mainCameraEffectPath: "string",
    isRemove: "bool",
  },
}
