//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAICrabMoveData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    speedLevel: "vint",
    turnSpeedOverride: "float",
    radiusMin: "float",
    radiusMax: "float",
    moveTimeMin: "float",
    moveTimeMax: "float",
    restTimeMin: "float",
    restTimeMax: "float",
    detectFrontDistance: "float",
  },
}
