//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAISpacialFacingMoveData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    speedLevel: "vint",
    rangeRadiusMin: "float",
    rangeRadiusMax: "float",
    restTimeMin: "float",
    restTimeMax: "float",
    facingMoveTurnInterval: "float",
    facingMoveMinAvoidanceVelecity: "float",
    obstacleDetectRange: "float",
    obstacleUpRange: "float",
    obstacleMaxAngle: "float",
    spacialFacingMoveProbability: "ConfigAISpacialFacingMoveProbability",
    canStartRangeByRaycast: "ConfigAIRaycastCondition[]",
  },
}
