//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicSingleEqualityCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicSingleCondition",
  Fields: {},
}
