//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCannon: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    closeOperationPageAfterFire: "bool",
    closePageDelay: "float",
    reminderVanishDelay: "float",
    fireInterval: "float",
    turningBtnPressBlockTime: "float",
    reminderTextMap: "string",
    TurnUpAbilityName: "string",
    TurnDownAbilityName: "string",
    TurnLeftAbilityName: "string",
    TurnRightAbilityName: "string",
    FireAbilityName: "string",
    ReleaseOccupyAbilityName: "string",
    OccupyGVName: "string",
    fireBtnIcon: "string",
    btnElementColorIndex: "vint",
  },
}
