//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAudioCamera: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    cameraPitchRtpcKey: "ConfigWwiseString",
  },
}
