//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigPartController: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    parts: "ConfigControlPart[]",
  },
}
