//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigDitherByBetweenCameraAndAvatar: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    detectDitherRange: "float",
  },
}
