//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAudioCityBlocks: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    musicSubStates: "map<string,ConfigWwiseString>",
  },
}
