//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuidePageCheckBaseCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuideCondition",
  Fields: {},
}
