//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigJobData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    jobMapData: "map<vint,map<vint,ConfigJob>>",
  },
}
