//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAudioAvatar: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    voiceSwitchKey: "ConfigWwiseString",
    bodyTypeSwitchKey: "ConfigWwiseString",
    weaponPutAwayAnimStateWhitelist: "string[]",
    energyRatioRtpc: "ConfigWwiseString",
    teamHpRTPC: "ConfigWwiseString",
    teamHpAliveRatio: "float",
    avatarAccessTypeSwitchGroup: "ConfigWwiseString",
    localAvatarSwitchValue: "ConfigWwiseString",
    remoteAvatarSwitchValue: "ConfigWwiseString",
    motionAvatarTypeRtpcKey: "ConfigWwiseString",
  },
}
