//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigEntityCollider: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    type: "EntityColliderType",
  },
}
