//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicUIntMultiValueStimulusHandler: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicMultiValueParameterizedStimulusHandler",
  Fields: {
    uintParams: "vuint[]",
  },
}
