import { ConfigDefault } from ".."

export const ConfigMainQuestScheme: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    id: "vuint",
    resId: "vuint",
    series: "vuint",
    type: "QuestType",
    mainQuestTag: "MainQuestTagType",
    activeMode: "PlayMode",
    titleTextMapHash: "vuint",
    descTextMapHash: "vuint",
    luaPath: "string",
    recommendLevel: "vuint",
    repeatable: "bool",
    suggestTrackMainQuestList: "vuint[]",
    suggestTrackOutOfOrder: "bool",
    rewardIdList: "vuint[]",
    showType: "QuestShowType",
    specialShowRewardId: "vuint[]",
    specialShowCondIdList: "vuint[]",
    specialShowQuestId: "vuint",
    chapterId: "vuint",
    taskId: "vuint",
    showRedPoint: "bool",
    activityId: "vuint",
    subQuests: "ConfigQuestScheme[]",
    talks: "ConfigTalkScheme[]",
    preloadLuaList: "vuint[]",
    forcePreloadLuaList: "vuint[]",
    freeStyleDic: "map<vuint,vint[]>",
    HALBECNDJMP: "ConfigDialogScheme[]",
  },
}
