//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCostumeAudio: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    wearVoice: "VoiceTriggerIdentity",
  },
}
