//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLevelEntity: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigEntity",
  Fields: {
    dropElemControlType: "DropElemControlType",
    abilities: "ConfigEntityAbilityEntry[]",
    avatarAbilities: "ConfigEntityAbilityEntry[]",
    teamAbilities: "ConfigEntityAbilityEntry[]",
    monsterAbilities: "ConfigEntityAbilityEntry[]",
    elemAmplifyDamage: "map<string,map<string,float>>",
    preloadMonsterEntityIDs: "vuint[]",
  },
}
