//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigHomePlaceColPath: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    placeColPath: "map<string,vuint[]>",
  },
}
