//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetIconBillboard: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBillboard",
  Fields: {
    iconName: "string",
    title: "string",
  },
}
