//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideCanGetPersonalLineKeyCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuideCondition",
  Fields: {
    value: "bool",
  },
}
