//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigEntityPoint: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    elementAbsorb: "string",
    elementPendant: "string",
    elementDrop: "string",
    bulletAim: "string",
    hitPoints: "string[]",
    selectedPoints: "string[]",
    ignoreTransform: "bool",
    selectedPointRadius: "float",
  },
}
