//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetStateDisableRadarHint: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGadgetStateAction",
  Fields: {},
}
