//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCameraSplineBasePoint: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    position: "Vector",
    eulerAngle: "Vector",
    dutch: "float",
    lengthRatio: "float",
    sList: "float[]",
    tList: "float[]",
  },
}
