//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigDangerZone: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigPolygonZone",
  Fields: {
    zonelist: "string[]",
  },
}
