//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicStringStimulusHandler: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicParameterizedStimulusHandler",
  Fields: {
    stringParam: "string",
  },
}
