//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigResourceCollectionContent: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    audioResourceList: "string[]",
    videoResourceList: "string[]",
  },
}
