//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigQTEStepBaseInterAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigQTEStepBaseAction",
  Fields: {
    interAction: "ConfigBaseInterAction",
  },
}
