//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGlobalShakeOff: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    reduceDurability: "float",
    interval: "float",
    shakeLifeTime: "float",
    shakeValue: "float",
    shakePeriod: "float",
    shakeSmoothRatio: "float",
    shakeAlongAngle: "float",
    shakeRotAngle: "float",
    shakeNoiseRatio: "float",
    shakeDirRatio: "float",
    shakeZRatio: "float",
  },
}
