//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigShowMessageAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseInterAction",
  Fields: {
    txtMapStr: "string",
  },
}
