//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetConsolePosition: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    transName: "string",
    rotation: "Vector",
  },
}
