//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideActivityGachaCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuideCondition",
  Fields: {
    percent: "vuint",
    opt: "GuideOperator",
  },
}
