//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigExternalVoiceInferiorItem: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    guid: "string",
    include: "bool",
  },
}
