//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAudioStateInterAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseInterAction",
  Fields: {
    stateGroup: "string",
    state: "string",
  },
}
