//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigFace: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    characterName: "string",
    baseFaceAnimation: "string",
    intervalFaceAnimation: "string",
    minInterval: "float",
    maxInterval: "float",
  },
}
