//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBulletPattern: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGadgetPattern",
  Fields: {
    triggerActions: "ConfigBaseGadgetTriggerAction[]",
    triggerLifeOverActions: "ConfigBaseGadgetTriggerAction[]",
    killByOther: "bool",
    dieDelayTime: "float",
    fireAISoundEvent: "bool",
    maxAutoKillDist: "float",
    enableCollisionDelay: "float",
  },
}
