//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigQTEStepPowerBarAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigQTEStepBaseAction",
  Fields: {
    changeValue: "vint",
  },
}
