import { ConfigDefault } from ".."

export const ConfigBaseCutscene: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    type: "CutsceneType",
    preTaskCfg: "ConfigCutscenePreTask",
    canSkip: "bool",
    can_skip_if_played: "bool",
    forceCanSkip: "bool",
    skipGeneralDialog: "bool",
    can: "bool",
    clearBlackScreen: "bool",
    fadeOutWhenFinish: "float",
    directTransmit: "bool",
    delayTransmit: "float",
    luaDataPath: "string",
    resPath: "string",
    castListPath: "string",
    entityBan: "string",
    ban_gadget_effect: "bool",
    startPosType: "CutsceneInitPosType",
    startOffset: "Vector",
    needXZEuler: "bool",
    needYEuler: "bool",
    keepCamera: "bool",
    useTargetPos: "bool",
    targetPos: "Vector",
    modifyLastPoseOffset: "bool",
    attackModeRecover: "bool",
    crowdLOD0List: "vint[]",
    enableCameraDisplacement: "bool",
    entityRuntimeID: "vuint",
    clearAvatarLocalGadget: "bool",
    disableGPUCulling: "bool",
    canPlayerLoop: "bool",
    mainQuestId: "vuint",
    disableAvatarLocalGadget: "bool",
  },
}
