//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigUIIndicator: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    icon: "TemplateParamString",
    distance_Show: "IndicatorDistanceInfoType",
    followMove: "bool",
    indicator: "IndicatorLogic[]",
  },
}
