//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetTurnState: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    angleAroundX: "float",
    angleAroundY: "float",
    angleAroundZ: "float",
    lerpCurveIndex: "vuint",
    lerpTime: "float",
  },
}
