//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCodexQuestItem: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    itemId: "vuint",
    itemType: "CodexQuestItemType",
    nextItemId: "vuint",
    speakerText: "ConfigCodexQuestText",
    speakerText2: "ConfigCodexQuestText",
    texts: "ConfigCodexQuestText[]",
    dialogs: "ConfigCodexQuestDialogSingle[]",
    dialogs2: "ConfigCodexQuestDialogSingle[]",
  },
}
