//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigFishingAimParabolaBulletMove: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBulletMove",
  Fields: {
    gravity: "float",
    initSpeed: "float",
    globalValueKey: "string",
  },
}
