//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLCBaseIntee: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    triggerShapeIn: "string",
    triggerShapeInHeight: "float",
    triggerShapeOut: "string",
    triggerShapeOutHeight: "float",
    triggerShapeInOffset: "Vector",
    triggerShapeOutOffset: "Vector",
    triggerShapeFreeInteraction: "string",
    triggerShapeFreeInteractionHeight: "float",
    triggerShapeFreeInteractionOffset: "Vector",
  },
}
