//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWidgetActivityGacha: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigWidgetUseAttachAbilityTrigger",
  Fields: {},
}
