//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigQTEStepCondActionGroup: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    condGroup: "ConfigQTEStepCondGroup",
    actions: "ConfigQTEStepBaseAction[]",
  },
}
