//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAudioListener: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    fakeAvatarDistance: "float",
    akListenerHeight: "float",
    obstructionRtpc: "ConfigWwiseString",
    focusAngleRtpc: "ConfigWwiseString",
    obstructionDetectRadius: "float",
    outreachCast: "ConfigAudioListenerOutreachCast",
    firstPersonListenerVolumeOffset: "float",
    thirdPersonListenerVolumeOffset: "float",
    defaultListenerVolumeOffset: "float",
  },
}
