//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigPS4TRC: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    defaultAge: "vint",
    contentRestrictionList: "ConfigContentRestriction[]",
  },
}
