//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMoveSyncInterval: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    lod0: "ConfigSpecificFloatValue",
    lod1: "ConfigSpecificFloatValue",
    lod2: "ConfigSpecificFloatValue",
  },
}
