//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigHomeworldBlockDefaultSave: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    blockId: "vint",
    persistentFurnitureList: "ConfigHomeworldFurnitureDefaultSave[]",
    deployFurniureList: "ConfigHomeworldFurnitureDefaultSave[]",
    deployNpcList: "vuint[]",
    furnitureSuiteList: "vuint[]",
    deployAnimalList: "vuint[]",
    isUnlocked: "bool",
    comfortValue: "vuint",
    weekendDjinnInfoList: "ConfigHomeworldDjinnInfoDefaultSave[]",
    dotPatternList: "vuint[]",
  },
}
