//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigJudgeAvatarElementType: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigJudgeNodeBase",
  Fields: {
    elementType: "ElementType",
  },
}
