//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMarkIcon: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    iconName: "string",
    materialIndex: "vuint",
    markType: "MarkType",
    effectName: "string",
    ignoreRaycastOnMap: "bool",
    title: "string",
    desc: "string",
    markLayer: "MarkOrder",
    visibilityOnRadar: "MarkVisibilityType",
    visibilityOnMap: "MarkVisibilityType",
    showHeightOnRadar: "bool",
    showOnLockedArea: "bool",
    pluginIconType: "MarkPluginIconType",
    fallbackMarkTipsType: "FallbackMarkTipsType",
  },
}
