//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAnimationCurve: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    keyframes: "ConfigKeyframe[]",
  },
}
