//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCoopBaseNode: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    coopNodeId: "vuint",
    coopNodeType: "CoopNodeType",
    nextNodeArray: "vuint[]",
  },
}
