//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigEliteShieldResistance: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    type: "string",
    damageRatio: "float[]",
    damageSufferRatio: "float[]",
  },
}
