//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAttackEvent: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    attackPattern: "ConfigBaseAttackPattern",
    attackInfo: "ConfigAttackInfo",
  },
}
