//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCodexQuestDialogSingle: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    text: "ConfigCodexQuestText",
    soundId: "vuint",
    nextItemId: "vuint",
  },
}
