//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCompoundInputAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseInputAction",
  Fields: {
    action1: "InputActionType",
    action2: "InputActionType",
    compoundType: "ActionCompoundType",
  },
}
