//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBattleFervorFactor_ByMonster: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBattleFervorFactor",
  Fields: {
    triggers: "ConfigBattleFervorUpdateTrigger_ByMonster[]",
  },
}
