//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideTheatreMechanicusInfoSelectCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuideCondition",
  Fields: {
    value: "vint",
    isSelect: "bool",
  },
}
