//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIFollowServerRouteSetting: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAITacticBaseSetting",
  Fields: {
    defaultSetting: "ConfigAIFollowServerRouteData",
    specification: "map<vint,ConfigAIFollowServerRouteData>",
  },
}
