//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBillboard: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    attachPoint: "string",
    offset: "Vector",
    offsetType: "BillboardOffsetType",
    radiusOffset: "float",
    enableSelfAdapt: "bool",
    showDistance: "float",
    markShowDistance: "float",
    nameShowDistance: "float",
    forceHideAllBars: "bool",
  },
}
