//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAudioListenerOutreachCast: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    range: "float",
    startAngle: "float",
    rayCount: "vint",
    rtpcNames: "ConfigWwiseString[]",
    offset: "Vector",
  },
}
