//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAITacticCondition: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    pose: "vint[]",
  },
}
