//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLocalGadgetMoveOp: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    targetPos: "Vector",
    time: "float",
    blendType: "TweenEaseType",
  },
}
