//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigClimateUI: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    climateInfoBtnIcon: "string",
    climateDialogTitle: "string",
    climateDialogDesc: "string",
    climateDialogLeftIcon: "string",
    climateDialogLeftBg: "string",
    showClimateMeter: "bool",
    climateMeterColorIndex: "vuint",
    climateMeterBgColorIndex: "vuint",
    screenEffectIndex: "vuint",
    climateInfoShowWithMeterType: "bool",
    uiLowWarningRatio: "float",
    uiLenLowIntensity: "float",
    uiMiddleWarningRatio: "float",
    uiLenMiddleIntensity: "float",
  },
}
