//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigTimer: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    lifeInfinite: "bool",
    startCheckTime: "float",
    checkInterval: "float",
    lifeTime: "float",
  },
}
