//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigScenePoint: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    type: "ScenePointType",
    gadgetId: "vuint",
    areaId: "vuint",
    pos: "Vector",
    rot: "Vector",
    tranPos: "Vector",
    tranRot: "Vector",
    unlocked: "bool",
    alias: "string",
    groupLimit: "bool",
    isModelHidden: "bool",
  },
}
