//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigQTEStepBaseAction: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    actionType: "QTEStepActionType",
    duration: "float",
  },
}
