//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicUIntStimulusHandler: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicParameterizedStimulusHandler",
  Fields: {
    uintParam: "vuint",
  },
}
