//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAvatarPerform: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    standby: "ConfigStandbyPerform",
  },
}
