//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAnimPatternPath: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    animPatternPaths: "map<string,string[]>",
  },
}
