//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCoopActionNode: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigCoopBaseNode",
  Fields: {
    actionList: "ConfigCoopAction[]",
  },
}
