import { ConfigDefault } from "../"

export const ConfigGraphicsRecommendSetting: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    performanceQuality: "string",
    virtualJoystickRadius: "float",
    levelStreamingConfig: "string",
    uiCacheConfig: "string",
    lightOnLevel: "LightLevel",
    requirements: "ConfigGraphicsRequirement[]",
    textureStreamingBudget: "float",
    enableCutsceneTextureStreaming: "vint",
    textureStreamingEnabled: "vint",
    textureStreamingOffset: "float",
    enableUICameraFullResolution: "vint",
    preloadUIScene: "vint",
    disableDoF: "vint",
    enableSubpass: "vint",
    usePerObjectLightInForward: "vint",
    renderResolutions: "ConfigRenderResolution[]",
    qualityLevel: "string",
    defaultVolatileGrade: "vint",
    avatarOutlineThresh: "float",
    avatarShadowThresh: "float",
    avatarMotionVectorThresh: "float",
    viewDistanceRatio: "float",
    grassQuality: "GrassQualityLevel",
    crowdSpawnDistance: "vint",
    crowdDespawnDistance: "vint",
    entityLODConfig: "string",
    deviceExtraFrameRate: "string[]",
    overrideRenderResGrade: "map<VolatileType,vint>",
  },
}
