//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuidePoint: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    ui_Indicator: "ConfigTemplateData",
    disableQuestArrow: "bool",
  },
}
