//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideAvatarChangeCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuideCondition",
  Fields: {
    configID: "vuint",
  },
}
