//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigContentRestriction: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    countryCode: "string",
    age: "vint",
  },
}
