//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBornByWorld: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBornType",
  Fields: {
    worldPos: "Vector",
    worldFwd: "Vector",
  },
}
