//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetMisc: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    chest: "ConfigChest",
    gear: "ConfigGear",
    forceField: "ConfigConstForceField",
    crystal: "ConfigCrystal",
    seal: "ConfigSeal",
    pickup: "ConfigPickup",
    windSeed: "ConfigWindSeed",
    cannon: "ConfigCannon",
    gadgetConsole: "ConfigGadgetConsole",
    autoDoor: "ConfigAutoDool",
    customGadgetNode: "ConfigCustomGadgetNode",
    escapeEffect: "string",
    guidePoint: "bool",
    isUIPoint: "bool",
    guidePointManagedByIndicator: "bool",
    guidePointType: "TargetIndicatorType",
    targetIndicatorYOffset: "float",
    guidePointConfig: "ConfigGuidePoint",
  },
}
