//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWidgetCaptureAnimal: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigWidgetUseAttachAbilityGroup",
  Fields: {
    captureTagArray: "vuint[]",
    isEnterCodex: "bool",
    isShowCodexEntry: "bool",
  },
}
