//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigElementView: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    elementColorIndex: "map<string,vint>",
    terrainGrassColor: "vuint",
  },
}
