//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigActionButton: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    type: "ActionBtnType",
    forceShow: "bool",
    onlyHandleInput: "bool",
  },
}
