//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigJudgeCurrentTime: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigJudgeNodeBase",
  Fields: {
    startTime: "float",
    endTime: "float",
  },
}
