//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigDummyAbilityOption: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    disableApplyModifierError: "bool",
  },
}
