//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLevelNpcBornPosNoGroup: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigLevelNpcBornPos",
  Fields: {},
}
