//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideVirtualDialActionCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuideCondition",
  Fields: {
    virtualDialAction: "vint",
  },
}
