//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMonsterAudio: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigCharacterAudio",
  Fields: {
    randomVariantSwitchGroup: "ConfigWwiseString",
    randomVariantSwitchValues: "ConfigWwiseString[]",
  },
}
