//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigEntityCommon: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    effectAttachShape: "ConfigEffectAttachShape",
    mass: "float",
    height: "float",
    modelHeight: "float",
    viewSize: "float",
    shadowViewSizeRatio: "float",
    overrideCullBoundsRadius: "float",
    affectedByWorld: "bool",
    checkInSurface: "bool",
    scale: "float",
    disableTickDistance: "float",
    forcePauseTickDistance: "float",
    shouldPauseAnimatorBeforeReady: "bool",
    canTriggerElementReactionText: "bool",
    useGrassDisplacement: "bool",
    muteElementStickUI: "bool",
    hasAfterImage: "bool",
    useDynamicBone: "bool",
    enableCrashDamage: "bool",
    clearAnimatorOnSetLightDeactive: "bool",
    clearAIOnSetLightDeactive: "bool",
    useFinalIK: "bool",
    elementReactionScale: "float",
    chargeBarHeightOffset: "float",
  },
}
