//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigEffectAttachSkinnedMesh: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigEffectAttachShape",
  Fields: {
    mesh: "string",
  },
}
