//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGlobalValueTurn: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGadgetTurn",
  Fields: {
    globalValueName: "string",
    avatarTargetPosGVKeyName: "string",
    avatarTargetPosMap: "map<vuint,Vector>",
  },
}
