//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMoveFollowNpc: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMoveFollowTarget",
  Fields: {
    configId: "vuint",
    questId: "vuint",
  },
}
