//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigBornDirectionType: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    angleOffset: "DynamicFloatVector",
    angleOffsetCorrect: "DynamicFloatVector",
    useCorrectDir: "bool",
    randomAngleHor: "float",
    randomAngleVer: "float",
    maxAngleType: "DirectionAngleType",
    maxAngle: "float",
  },
}
