import { ConfigDefault } from "../"

export const ConfigLevelMonsterUnit: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    groupId: "vuint",
    mapInstId: "vuint",
    spawnedByEvtPattern: "bool",
    routeId: "vint",
    aiPatrolSetting: "ConfigLevelMonsterAIPatrol",
    aiGroupID: "vuint",
    overrideDefendAreaRange: "bool",
    defendAreaRange: "float",
    overrideForceAlertDistance: "bool",
    forceAlertDistanceLimit: "float",
    defendAreaID: "vuint",
    wanderAreaID: "vuint",
    overrideClearThreatTargetDistance: "bool",
    clearThreatTargetDistance: "float",
    aiNeuronSetting: "string",
    aiSensingTemplate: "string",
    forceCombatOnSpawn: "bool",
    disableWander: "bool",
    standOnDistantMesh: "bool",
    landingPointID: "vuint",
    extractionPointID: "vuint",
    overrideUseNavmesh: "bool",
    useNavmesh: "bool",
    overrideToTheMoon: "bool",
    useToTheMoon: "bool",
    billboard_HasUIBar: "bool",
    billboard_ShowUIBarDis: "float",
    billboard_HideUIBarDis: "float",
    billboard_UIBarNeedEnterCombat: "bool",
    billboard_HpBarStyle: "HpBarStyle",
    billboard_MultiBarSortId: "vuint",
    billboard_MultiBarNum: "vuint",
    reuseNotRemoveAbilityTag: "string",
    hasSneakIndicator: "bool",
  },
}
