import { ConfigDefault } from "../"

export const ConfigAudioWeather: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    transitionRtpcKey: "ConfigWwiseString",
    dominantStateName: "ConfigWwiseString",
    dominantSwitchName: "ConfigWwiseString",
    dominantRtpcKey: "ConfigWwiseString",
    dominantStateNameWithoutDelay: "ConfigWwiseString",
    dominantRtpcKeyWithoutDelay: "ConfigWwiseString",
    timeOfDayRtpcKey: "ConfigWwiseString",
    avatarSpeechEvent: "ConfigWwiseString",
    enable_default_weather_state_setting: "bool",
    default_weather_state: "AudioWeatherProperties",
    weatherStateMap: "map<string,AudioWeatherProperties>",
    workset1: "AudioWeatherWorkSet",
    workset2: "AudioWeatherWorkSet",
    nearThunderStart: "AudioOneTimeEvent",
    nearThunderEnd: "AudioOneTimeEvent",
    distantThunderStart: "AudioOneTimeEvent",
    distantThunderEnd: "AudioOneTimeEvent",
    skyThunder: "AudioOneTimeEvent",
    worksetSwitchKey: "ConfigWwiseString",
    windSpeedRtpcKey: "ConfigWwiseString",
    windDirectionRtpcKey: "ConfigWwiseString",
    climateRtpcKey: "ConfigWwiseString",
    climateRTPCMap: "map<string,string>",
    weatherVoiceTriggers: "AudioWeatherVoTrigger[]",
    thunderVoiceTrigger: "VoiceTriggerIdentity",
    thunderVoiceCooldown: "vuint",
    enviroTimeRtpcKey: "ConfigWwiseString",
    angleBetweenWindAndListenerRtpcKey: "ConfigWwiseString",
    angleStaticUpdateRate: "float",
    angleDynamicUpdateRate: "float",
  },
}
