import { ConfigDefault } from "../"

export const ConfigDie: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    hasAnimatorDie: "bool",
    muteAllShaderDieEff: "bool",
    fallWhenAirDie: "bool",
    dieEndTime: "float",
    dieForceDisappearTime: "float",
    dieDisappearEffect: "string",
    dieDisappearEffectDelay: "float",
    dieShaderData: "E_ShaderData",
    dieShaderEnableDurationTime: "float",
    dieShaderDisableDurationTime: "float",
    dieModelFadeDelay: "float",
    useRagDoll: "bool",
    ragDollDieEndTimeDelay: "float",
    startDieEndAtOnce: "bool",
    notSendDieTrigger: "bool",
    ignoreElementDie: "bool",
    muteHitBox: "bool",
    dieDenyLockOn: "bool",
    dieIsGhostToEnemy: "bool",
    dieIgnoreTriggerBullet: "bool",
    muteBillboard: "bool",
    mutePushCollider: "bool",
    dropWeaponImmediately: "bool",
    muteHdmesh: "bool",
  },
}
