//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicShifter: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    targetSongId: "vint",
    rootConditionId: "vint",
  },
}
