//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIBirdCirclingSetting: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAITacticBaseSetting",
  Fields: {
    defaultSetting: "ConfigAIBirdCirclingData",
    specification: "map<vint,ConfigAIBirdCirclingData>",
  },
}
