import { ConfigDefault } from "../"

export const ConfigPerformanceSetting: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    scenePropCacheCount: "vint",
    bundleUnloadLRURetireTime: "float",
    bundleUnloadLRURetireSize: "vint",
    bundleUnloadLRUCapcity: "vint",
    GameObjectPoolCount: "vint",
    useFinalIK: "bool",
    enableAudioSurfaceMultiprobing: "bool",
    enableAudioFocusAttenuation: "bool",
    enableAudioOcclusionRacasts: "bool",
    enableAudioListenerOutreachDetetion: "bool",
    cachedEntityTime: "float",
    cachedEntityDist: "float",
    useHeadControl: "bool",
    useAvatarGrassDisplacement: "bool",
    useOtherEnttiyGrassDisplacement: "bool",
    useWindZoneGrassDisplacement: "bool",
    useRagdoll: "bool",
    useFBIK: "bool",
    windFlagMaxQualityLevel: "vint",
    useDynamicBone: "bool",
    climbIKQualityLevel: "vint",
    useClimbIK: "bool",
    useMoveIK: "bool",
    useEffectLOD: "bool",
    ragdollLimitCount: "vint",
    ragdollPoolSize: "vint",
    ragdollPoolSameIdSize: "vint",
  },
}
