//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicUInt32InequalityCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicUInt32Condition",
  Fields: {},
}
