//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigRenderResolution: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    width: "vint",
    height: "vint",
    secondWidth: "vint",
    secondHeight: "vint",
    perfCostRatio: "float",
  },
}
