//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigFireGrassAirflowField: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAirflowField",
  Fields: {
    enable: "bool",
    triggerNum: "vuint",
    height: "float",
    heightSpeed: "float",
  },
}
