//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIMeleeChargeData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    speedLevel: "vint",
    turnSpeedOverride: "float",
    startDistanceMin: "float",
    startDistanceMax: "float",
    stopDistance: "float",
    innerDistance: "float",
    speedLevelInner: "vint",
    useMeleeSlot: "bool",
  },
}
