//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideEndTaskAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuideAction",
  Fields: {
    taskName: "string",
  },
}
