//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLightComponent: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    lightType: "string",
    range: "float",
    colorR: "float",
    colorG: "float",
    colorB: "float",
    angle: "float",
    intensity: "float",
    indirectMult: "float",
  },
}
