//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideDelayFinishCondition: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGuideCondition",
  Fields: {
    delayTime: "float",
  },
}
