//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigRecordEmoParameters: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    eyeInfo: "Vector[]",
    emoFuncs: "ConfigRecordEmoFunc[]",
  },
}
