//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIExtractionData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    speedLevel: "vint",
    extractionDistance: "float",
    extractionAngleMax: "float",
    extractionAngleMin: "float",
    triggerDistance: "float",
    killSelfTime: "float",
  },
}
