//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWidgetToyCrystal: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigWidgetUseAttachAbilityTrigger",
  Fields: {
    energyCost: "float",
    meterType: "RegionalPlayVarType",
  },
}
