import { ConfigDefault } from "../"

export const ConfigAudioCombat: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    impactEvent: "AudioOneTimeEvent",
    arrowImpactHeadEvent: "AudioOneTimeEvent",
    bushImpactEvent: "AudioOneTimeEvent",
    treeImpactEvent: "AudioOneTimeEvent",
    putAwayWeaponEvent: "ConfigWwiseString",
    strikeTypeSwitchKey: "ConfigWwiseString",
    strikeTypeSwitchMap: "map<StrikeType,ConfigWwiseString>",
    strikeTypeSwitchDefault: "ConfigWwiseString",
    elementTypeSwitchKey: "ConfigWwiseString",
    elementTypeSwitchMap: "map<ElementType,ConfigWwiseString>",
    elementTypeSwitchDefault: "ConfigWwiseString",
    hitSceneEvent: "AudioOneTimeEvent",
    whetherRecurringSwitchKey: "ConfigWwiseString",
    hitOneshotSwitchValue: "ConfigWwiseString",
    hitRecurringSwitchValue: "ConfigWwiseString",
    entityFadeOutEvent: "ConfigWwiseString",
    patrollerTemperatureRtpc: "ConfigWwiseString",
    patrollerAwareEvent: "ConfigWwiseString",
    patrollerAlertEvent: "ConfigWwiseString",
    patrollerCalmEvent: "ConfigWwiseString",
    impactOverrideEvents: "AudioImpactOverrideEvent[]",
    arrowImpactOverrideEvents: "AudioImpactOverrideEvent[]",
    hittingSceneIgnoreList: "vuint[]",
    isMostDangerousRtpcKey: "ConfigWwiseString",
    isEndingHitRtpcKey: "ConfigWwiseString",
    cirtDamageRateRtpcKey: "ConfigWwiseString",
    critical_damage: "CriticalDamageConfig",
    threatVsingleInitRtpcKey: "ConfigWwiseString",
    mostDangerousForMonsterAtkeeRtpcKey: "ConfigWwiseString",
    battleFervorData: "ConfigBattleFervor",
    attackResultData: "ConfigAudioAttackResult",
    avatarAttackerImpactOverrideMap: "map<string,AudioImpactOverrideEvent_AvatarAttacker>",
    endHint: "EndHintConfig",
  },
}
