//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIFacingMoveWeight: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    stop: "float",
    forward: "float",
    back: "float",
    left: "float",
    right: "float",
  },
}
