//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIFollowScriptedPathSetting: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAITacticBaseSetting",
  Fields: {
    defaultSetting: "ConfigAIFollowScriptedPathData",
    specification: "map<vint,ConfigAIFollowScriptedPathData>",
  },
}
