//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAudioDialog: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    reactions: "AudioDialogReaction[]",
  },
}
