//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCustomGadgetNode: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    customGadgetType: "CustomGadgetType",
    cameraSettings: "CustomGadgetCameraSettings",
    slotMap: "map<string,CustomGadgetNodeSlot>",
  },
}
