//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicCamera: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    resName: "string",
    conditionList: "CameraPlayCondition[]",
    style: "vuint",
    disableDither: "bool",
  },
}
