//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigWidgetToyClintCollector: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseWidgetToy",
  Fields: {
    targetType: "CollectorType",
    elementType: "ElementType",
    rechargePoints: "vuint",
    maxPoints: "vuint",
    effectGadgetId: "vuint",
    useGadgetId: "vuint",
    allowOtherWorld: "bool",
  },
}
