//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigRuleLimitFrameGlobal: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAudioEventCullingRuleBase",
  Fields: {
    limitFrame: "vint",
  },
}
