//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicFloatStimulusHandler: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicParameterizedStimulusHandler",
  Fields: {
    floatParam: "float",
  },
}
