//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAttackDoubleTrail: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAttackTrail",
  Fields: {
    trail2Name: "string",
    trailStart2Name: "string",
  },
}
