//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCameraSplineCatmullTarget: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigCameraSplineBaseTarget",
  Fields: {},
}
