//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigRegionalPlayVarData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    varType: "RegionalPlayVarType",
    initValue: "float",
  },
}
