//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGuideContextList: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    mainPageBlack: "string[]",
    dialogBlack: "string[]",
    globalWhite: "string[]",
    intervalBlack: "string[]",
    prefabAndHintWhite: "string[]",
  },
}
