//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigSimpleMove: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMove",
  Fields: {
    constSpeedRatio: "float",
    followReferenceSystem: "bool",
  },
}
