//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCameraRadialBlur: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    power: "float",
    blurTime: "float",
    fadeTime: "float",
  },
}
