//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigRandomTalkScheme: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    id: "vuint",
    freeStyleList: "vint[]",
  },
}
