//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigShapeCircle: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseShape",
  Fields: {
    radius: "float",
  },
}
