//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigJudgeAvatarWeaponType: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigJudgeNodeBase",
  Fields: {
    weaponType: "string",
  },
}
