//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLevelBlockMeta: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    blockID: "vuint",
    isIgnoreBlockPosition: "bool",
    blockCenterX: "vint",
    blockCenterZ: "vint",
    blockLevelMonsterDataPathHashSuffix: "vuint",
    blockLevelMonsterDataPathHashPre: "byte",
    blockLevelRouteDataPathHashSuffix: "vuint",
    blockLevelRouteDataPathHashPre: "byte",
  },
}
