//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCCD: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    type: "CCDType",
    detectCD: "float",
  },
}
