//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigOpenBlossomMarkInterAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseInterAction",
  Fields: {
    openAll: "bool",
  },
}
