//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetDamageByAttackValue: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseGadgetTriggerAction",
  Fields: {
    born: "ConfigBornType",
    attackInfo: "ConfigAttackInfo",
  },
}
