//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIReturnToBornPosData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    speedLevel: "vint",
    fadeoutBeginTime: "float",
    fadeoutEndTime: "float",
    spacial: "bool",
    performTime: "float",
  },
}
