//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAudioNpc: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    defaultVocalBoneName: "string",
  },
}
