//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLocalTriggerMeta: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    vectorParam: "Vector",
    floatParam: "float",
    stringParam: "string",
  },
}
