//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigTileElement: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    elementType: "ElementType",
    elementDurability: "float",
    isElementDurabilityMutable: "bool",
  },
}
