//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigIntee: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    useTrigger: "bool",
    useInteractionTrigger: "bool",
    usePushCollider: "bool",
    useHeadControlTrigger: "bool",
    triggerRadius: "float",
    triggerHeight: "float",
    interactionTriggerRadius: "float",
    headCtrlRadius: "float",
    triggerOffset: "Vector",
  },
}
