//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIUISetting: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    hasDirectionIndicator: "bool",
  },
}
