//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAISpacialProbeData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    speedLevel: "vint",
    turnSpeedOverride: "float",
    cdMax: "float",
    cdMin: "float",
    terrainOffsetMin: "float",
    terrainOffsetMax: "float",
    distanceFromBorn: "float",
    distanceFromCurrentMin: "float",
    distanceFromCurrentMax: "float",
    probeNumberMin: "vint",
    probeNumberMax: "vint",
  },
}
