//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLBaseMark: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    priority: "vint",
    views: "ConfigVBaseMark[]",
  },
}
