//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigCoopSelectNode: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigCoopBaseNode",
  Fields: {
    selectList: "CoopSelectNodeContent[]",
    delayMoveNext: "bool",
  },
}
