//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAILandingData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    speedLevel: "vint",
    landingAngleMax: "float",
    landingAngleMin: "float",
    landingTerrainAltitude: "float",
  },
}
