//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigJudgeAvatarConfigID: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigJudgeNodeBase",
  Fields: {
    configIDs: "vuint[]",
  },
}
