//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigDynamicTalent: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    talentName: "string",
  },
}
