//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAIFollowScriptedPathData: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    turnSpeedOverrideWalk: "float",
    turnSpeedOverrideRun: "float",
    spacial: "bool",
    spacialRoll: "bool",
  },
}
