//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigLightAttach: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    attachPoint: "string",
    localPosX: "float",
    localPosY: "float",
    localPosZ: "float",
    localRotX: "float",
    localRotY: "float",
    localRotZ: "float",
    localRotW: "float",
  },
}
