//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigKeyboardLayoutItem: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    keyCodeFriendlyName: "map<ConfigKeyCode,string>",
  },
}
