//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGlobalDither: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    ditherMinRange: "float",
    ditherMaxRange: "float",
    defaultDetectHeight: "float",
    detectHeightCheckStep: "vuint",
  },
}
