//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigAISkillSetting: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    skillEliteSet: "map<byte,vuint[]>",
  },
}
