//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigGadgetStateEnableGadgetIntee: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigGadgetStateAction",
  Fields: {
    enable: "bool",
  },
}
