//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigKeyframe: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    time: "float",
    value: "float",
    inTangent: "float",
    outTangent: "float",
  },
}
