//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigSkipUnindexedEffectCreation: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    skipUnindexedEffectCreationByDistance: "ConfigSkipUnindexedEffectCreationByDistance",
  },
}
