//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigPlayPostEffectAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigBaseInterAction",
  Fields: {
    assetName: "string",
    isRemove: "bool",
  },
}
