//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigMusicMultiValueParameterizedStimulusHandler: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigMusicParameterizedStimulusHandler",
  Fields: {},
}
