//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigClimateMisc: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    dampingTime: "float",
    fadeSpeed: "float",
  },
}
