//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigEffectAttachBox: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigEffectAttachShape",
  Fields: {
    emitFrom: "ParticleShapeType",
    scaleX: "float",
    scaleY: "float",
    scaleZ: "float",
  },
}
