//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ControlEmotion: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    toggleEmoSync: "bool",
    toggleBlink: "bool",
    toggleEyeKey: "bool",
  },
}
