//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ContextActionSelectMonsterMark: ConfigDefault = {
  attribute: [],
  baseClass: "ContextAction",
  Fields: {
    monsterId: "vuint",
    needTrack: "bool",
  },
}
