//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ContextActionSetAnimatorTrigger: ConfigDefault = {
  attribute: [],
  baseClass: "ContextAction",
  Fields: {
    uiElement: "ActivityBannerUIElementType",
    triggerName: "string",
    setOrReset: "bool",
  },
}
