//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ContextActionSelectLegendQuest: ConfigDefault = {
  attribute: [],
  baseClass: "ContextAction",
  Fields: {
    legendQuestId: "vuint",
  },
}
