//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ContextActionSelectChapterOngoingMainQuest: ConfigDefault = {
  attribute: [],
  baseClass: "ContextAction",
  Fields: {
    chapterId: "vuint",
  },
}
