//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ContextConditionNot: ConfigDefault = {
  attribute: [],
  baseClass: "ContextCondition",
  Fields: {
    condition: "ContextCondition",
  },
}
