//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ContextActionSelectMainQuest: ConfigDefault = {
  attribute: [],
  baseClass: "ContextAction",
  Fields: {
    mainQuestId: "vuint",
  },
}
