//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ContextActionReportActivityBuriedPoint: ConfigDefault = {
  attribute: [],
  baseClass: "ContextAction",
  Fields: {
    activityId: "vuint",
    buttonId: "vuint",
    scheduleId: "vuint",
    additionalInfo: "string",
  },
}
