//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ContextConditionOr: ConfigDefault = {
  attribute: [],
  baseClass: "ContextCondition",
  Fields: {
    conditions: "ContextCondition[]",
  },
}
