//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ContextActionSelectTransPoint: ConfigDefault = {
  attribute: [],
  baseClass: "ContextAction",
  Fields: {
    pointId: "vuint",
    sceneId: "vuint",
  },
}
