//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CoopSubStartPoint: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    id: "vuint",
    coopInteractionId: "vuint",
  },
}
