//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CoopCondGroup: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    condCombType: "LogicType",
    coopCondList: "CoopCond[]",
  },
}
