//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CoopSavePoint: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    id: "vuint",
    isEnd: "bool",
  },
}
