//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CoopTemperament: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    value: "vuint",
    ratio: "float",
  },
}
