//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CurLocalAvatarMixinV2: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    modifierName: "string",
  },
}
