//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CustomGadgetNodeSlot: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    namedTransform: "string",
    slotType: "CustomGadgetNodeSlotType",
    slotConfigId: "vuint",
  },
}
