//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CustomSlotConfig: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    slotID: "vuint",
    optionalPartsIdList: "vuint[]",
    isNecessary: "bool",
    defaultPartsIdList: "vuint[]",
    passPartIdList: "vuint[]",
    initPartsId: "vuint",
  },
}
