//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DebugLog: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    content: "string",
  },
}
