//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DebugBlletinInfo: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    id: "vuint",
    board_id: "vuint",
    content: "string",
    author: "string",
    create_time: "string",
  },
}
