//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DebugBoardInfo: ConfigDefault = {
  attribute: [],
  baseClass: "DebugBlletinInfo",
  Fields: {
    type: "vuint",
    title: "string",
    location: "string",
    scene_id: "vuint",
  },
}
