//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DeductStamina: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    value: "DynamicFloat",
    swimCheck: "bool",
  },
}
