//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DirectionTarDistanceScatter: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    maxDistance: "float",
    maxScatterAngle: "float",
    centerRote: "float",
    randomRote: "float",
  },
}
