//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DoTileAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    actionID: "string",
  },
}
