//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DropSubfield: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    subfieldName: "string",
  },
}
