//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DummyMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    actionList: "ConfigAbilityAction[][]",
  },
}
