//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DungeonExit: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigScenePoint",
  Fields: {
    entryPointId: "vuint",
  },
}
