//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DvalinS01PathEffsInfo: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    flyState: "vint",
    effectName: "string",
    pathCenter: "bool",
    intervalMax: "vint",
    intervalMin: "vint",
    numMax: "vint",
    numMin: "vint",
    rangeMax: "float",
    rangeMin: "float",
    eularMax: "float",
    eularMin: "float",
    yScale: "float",
  },
}
