//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ElementConvertToChargeBarValueMixinItem: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    elementType: "ElementType",
    ratio: "float",
  },
}
