//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ElementBatchPredicated: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    elementTypeArr: "ElementType[]",
    successActions: "ConfigAbilityAction[]",
    failActions: "ConfigAbilityAction[]",
  },
}
