//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EnableRocketJump: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    type: "RocketJumpType",
    enable: "bool",
    extention: "RocketJumpExt",
    uiEffect: "bool",
  },
}
