//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EnableCharacterMoveOnWaterMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {},
}
