//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EnablePushColliderName: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    pushColliderNames: "string[]",
    setEnable: "bool",
  },
}
