//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EnableCameraDof: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    enableDof: "bool",
  },
}
