//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EntityMarkShowTypeMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    markType: "EntityMarkType",
  },
}
