//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EquipAffixStart: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    CD: "DynamicFloat",
    equipAffixDataID: "vuint",
  },
}
