//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ExecuteGroupTrigger: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    sourceName: "string",
    param1: "vint",
    param2: "vint",
    param3: "vint",
  },
}
