//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FieldEntityCountChangeMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    campTargetType: "TargetType",
    forceTriggerWhenChangeAuthority: "bool",
    targetPredicates: "ConfigAbilityPredicate[]",
    onFieldEnter: "ConfigAbilityAction[]",
    onFieldExit: "ConfigAbilityAction[]",
  },
}
