//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FireAISoundEvent: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    volume: "float",
  },
}
