//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FireAvatarBeingHitAfterImage: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    effectIndex: "vuint",
  },
}
