//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FireEffectForStorm: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    born: "ConfigBornType",
    height: "float",
  },
}
