//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FocusAssistanceGroup: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    ps4: "FocusAssistance",
    ps5: "FocusAssistance",
    other: "FocusAssistance",
  },
}
