//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FocusAssistance: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    useFocusSticky: "bool",
    useAutoFocus: "bool",
    useGyro: "bool",
  },
}
