//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const GetHealAmountToGlobalValue: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    type: "GlobalValueChangeType",
    key: "string",
  },
}
