//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const GetInteractIdToGlobalValue: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    key: "string",
  },
}
