//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const GetPos: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    key: "string",
    posType: "GetPosType",
  },
}
