//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const GetTeamTotalMaxEnergyToOverridemap: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    teamType: "TeamType",
    overrideMapKey: "string",
  },
}
