//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const HideUIBillBoard: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    hide: "bool",
  },
}
