//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IgnoreMoveColToRockCol: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    ignore: "bool",
  },
}
