//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IndicatorConditionAvatarDistance: ConfigDefault = {
  attribute: [],
  baseClass: "IndicatorCondition",
  Fields: {
    distance: "TemplateParamFloat",
  },
}
