//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IndicatorConditionAllowInteract: ConfigDefault = {
  attribute: [],
  baseClass: "IndicatorCondition",
  Fields: {
    allowInteract: "bool",
  },
}
