//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IndicatorConditionSceneTransPointLockState: ConfigDefault = {
  attribute: [],
  baseClass: "IndicatorCondition",
  Fields: {
    unlocked: "bool",
  },
}
