//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const InteractTriggerAbility: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    abilityName: "string",
  },
}
