//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const KillGadget: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    gadgetInfo: "SelectTargetsByChildren",
  },
}
