//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ModifyElementDecrateMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    group: "string",
  },
}
