//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MonsterDefendAudio: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    onDefendSucceded: "ConfigWwiseString",
  },
}
