//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MoveStateMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    type: "MoveStateMixinType",
  },
}
