//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const OnLevelTagChangeMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    actions: "ConfigAbilityAction[]",
  },
}
