//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const OnParentAbilityStartMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    actionList: "ConfigAbilityAction[]",
  },
}
