//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const OverrideAttackEventMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    overrideAttackEvent: "string",
  },
}
