//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const PlayerCustomOptionConfig: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigPerfItemOverrideInfoBase",
  Fields: {
    optionTextName: "string[]",
    perfCostRatio: "float[]",
  },
}
