//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const PlayEmoSync: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    dialogID: "vuint",
    emoSyncAssetPath: "string",
  },
}
