//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const PushInterActionByConfigPath: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    cfgPath: "string",
    isExternal: "bool",
  },
}
