//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const QuestContentEx: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    type: "QuestContentType",
    param: "vint[]",
    count: "vuint",
  },
}
