//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const QuestGuideEx: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    type: "QuestGuideType",
    autoGuide: "QuestGuideAuto",
    param: "string[]",
    guideScene: "vuint",
    guideStyle: "QuestGuideStyle",
    guideLayer: "QuestGuideLayer",
  },
}
