//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RegistToStageScript: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    alias: "string",
  },
}
