//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ReleaseAIActionPoint: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    pointType: "ActionPointType",
  },
}
