//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RelyOnElementMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    elementType: "ElementType",
  },
}
