//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RemoveVelocityForce: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    forces: "VelocityForceType[]",
  },
}
