//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ResetClimateMeter: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    climateType: "JsonClimateType",
  },
}
