//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ResetAIThreatBroadcastRange: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    range: "DynamicFloat",
  },
}
