//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ResetAnimatorTrigger: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    triggerID: "string",
  },
}
