//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ResetAIResistTauntLevel: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    resistTauntLevel: "TauntLevel",
  },
}
