//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ReviveStamina: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    value: "DynamicFloat",
  },
}
