//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RocketJumpExt: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    xzMultiplier: "float",
    yMultiplier: "float",
  },
}
