//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RocketJumpMixin: ConfigDefault = {
  attribute: [],
  baseClass: "BaseSwitchMixin",
  Fields: {
    type: "RocketJumpType",
    extention: "RocketJumpExt",
    uiEffect: "bool",
  },
}
