//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RunGM: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    gm: "string",
    flush: "bool",
  },
}
