//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RushMove: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    toPos: "ConfigBornType",
    minRange: "float",
    maxRange: "float",
    timeRange: "float",
  },
}
