//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SceneVehicleSummonPoint: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigScenePoint",
  Fields: {
    vehicleType: "VehicleType",
    vehicleGadgetId: "vuint",
    bornPointList: "Vector[]",
    bornRotateList: "Vector[]",
    vehicleRadius: "float",
    titleTextID: "string",
    mapMarkType: "SceneVehicleSummonPointMapMarkType",
  },
}
