//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SelectTargetsByLCTrigger: ConfigDefault = {
  attribute: [],
  baseClass: "SelectTargets",
  Fields: {
    campTargetType: "TargetType",
  },
}
