//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SelectTargetsBySelfGroup: ConfigDefault = {
  attribute: [],
  baseClass: "SelectTargets",
  Fields: {
    operation: "BitwiseOperator",
    value: "vuint",
    dynamicValue: "DynamicInt",
    useBinary: "bool",
    compareType: "RelationalOperator",
  },
}
