//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SelectActionPointByID: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigActionPointSelectType",
  Fields: {
    actionPointID: "vuint",
  },
}
