//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SelectActionPointByTargetPos: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigActionPointSelectType",
  Fields: {
    distance: "float",
  },
}
