//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SendEffectTrigger: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    parameter: "string",
    type: "AnimatorParamType",
    value: "vint",
    effectPattern: "DynamicString",
    floatValue: "float",
    notInvokeWhenNotAlive: "bool",
  },
}
