//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetAvatarCanShakeOff: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    canShakeOff: "bool",
  },
}
