//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetAvatarHitBuckets: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    overrideAvatarHitBucketSetting: "ConfigAvatarHitBucketSetting",
  },
}
