//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetAnimatorInt: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    intID: "string",
    value: "DynamicFloat",
    persistent: "bool",
  },
}
