//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetAISkillGCD: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    value: "float",
  },
}
