//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetAISkillCDAvailableNow: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    skillIDs: "vuint[]",
  },
}
