//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetCombatFixedMovePoint: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    setPoint: "bool",
    toPos: "ConfigBornType",
  },
}
