//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetDvalinS01FlyState: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    toState: "vint",
  },
}
