//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetEntityScale: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    scale: "float",
  },
}
