//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetGlobalValueList: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    globalValueList: "GlobalValuePair[]",
  },
}
