//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetGlobalDir: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    key: "string",
    born: "ConfigBornType",
    setTarget: "bool",
  },
}
