//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetKeepInAirVelocityForce: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    setEnable: "bool",
  },
}
