//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetLogicStateValue: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    logicStateName: "string",
    value: "DynamicFloat",
  },
}
