//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetOvergrowDamgeToOverrideMap: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    reactionTriggerType: "ReactionTriggerType",
  },
}
