//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetPoseInt: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    intID: "string",
    value: "vint",
  },
}
