//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetPaimonTempOffset: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    from: "PaimonRequestFrom",
    offSetPos: "Vector",
    time: "float",
  },
}
