//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetSpecialCamera: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    enable: "bool",
    specialCameraName: "string",
  },
}
