//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SetWeaponAttachPointRealName: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    partName: "string",
    realName: "string",
  },
}
