//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ShaderLerpMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    type: "E_ShaderData",
  },
}
