//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ShowExtraAbility: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    skillID: "vuint",
  },
}
