//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ShowProgressBarAction: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    show: "bool",
  },
}
