//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ShowTextMap: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    id: "string",
  },
}
