//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SpawnAttach: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    enable: "bool",
    attachName: "string",
  },
}
