//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SphereTileShapeInfo: ConfigDefault = {
  attribute: [],
  baseClass: "TileShapeInfo",
  Fields: {
    radius: "float",
  },
}
