//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TemplateParamString: ConfigDefault = {
  attribute: [],
  baseClass: "TemplateParam",
  Fields: {
    originValue: "string",
  },
}
