//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TemplateParamFloat: ConfigDefault = {
  attribute: [],
  baseClass: "TemplateParam",
  Fields: {
    originValue: "float",
  },
}
