//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TriggerRageSupportMixin: ConfigDefault = {
  attribute: [],
  baseClass: "TriggerTypeSupportMixin",
  Fields: {
    dampRatio: "float",
    addRatio: "float",
    maxValue: "float",
    minValue: "float",
  },
}
