//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TriggerSetCastShadow: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    castShadow: "bool",
  },
}
