//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TriggerSetShadowRamp: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    useShadowRamp: "bool",
    specialMats: "string[]",
  },
}
