//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TriggerCrystalLinkAbility: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    id: "vuint",
  },
}
