//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TriggerResistDamageTextMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    elementTypes: "ElementType[]",
  },
}
