//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TriggerTypeSupportMixin: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityMixin",
  Fields: {
    duration: "float",
    radius: "float",
  },
}
