//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TriggerTaunt: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    tauntLevel: "TauntLevel",
    careValue: "float",
  },
}
