//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TriggerSetPassThrough: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    passThrough: "bool",
  },
}
