//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TurnDirection: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    turnMode: "TurnMode",
  },
}
