//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const UnlockControllerConditions: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigTalentMixin",
  Fields: {
    conditionName: "string",
  },
}
