//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const UnlockTalentParam: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigTalentMixin",
  Fields: {
    abilityName: "string",
    talentParam: "string",
  },
}
