//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const UseItem: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    itemId: "vuint",
    itemNum: "vuint",
  },
}
