//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const UseSkillEliteSet: ConfigDefault = {
  attribute: [],
  baseClass: "ConfigAbilityAction",
  Fields: {
    skillEliteSetID: "byte",
  },
}
