//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const VoiceSound: ConfigDefault = {
  attribute: [],
  baseClass: null,
  Fields: {
    personality: "VoicePersonality",
    positioning: "VoicePositioning",
    soundName: "ConfigWwiseString",
  },
}
