import { ConfigDefault } from "."

export const CreatureExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: "EntityExcelConfig",
  Fields: {
    hpBase: "float",
    attackBase: "float",
    defenseBase: "float",
    critical: "float",
    antiCritical: "float",
    criticalHurt: "float",
    fireSubHurt: "float",
    grassSubHurt: "float",
    waterSubHurt: "float",
    elecSubHurt: "float",
    windSubHurt: "float",
    iceSubHurt: "float",
    rockSubHurt: "float",
    fireAddHurt: "float",
    grassAddHurt: "float",
    waterAddHurt: "float",
    elecAddHurt: "float",
    windAddHurt: "float",
    iceAddHurt: "float",
    rockAddHurt: "float",
    propGrowCurves: "FightPropGrowConfig[]",
    elementMastery: "float",
    physicalSubHurt: "float",
    physicalAddHurt: "float",
    prefabPathHashSuffix: "vuint",
    prefabPathHash: "vuint",
  },
}
