//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigBulletMoveAngle: TypeIndexDefault = {
  "0": "ConfigBulletMoveAngle",
  "1": "ConfigBulletMoveAngleByVelocity",
  "2": "ConfigBulletMoveAngleRotating",
}
