//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigPerfItemOptionArrayInfoBase: TypeIndexDefault = {
  "0": "ConfigPerfItemOptionArrayInfoBase",
  "1": "ConfigPerfNumberItemOptionArrayInfo",
  "2": "ConfigPerfNumberArrayItemOptionArrayInfo",
  "3": "ConfigPerfStringKeyItemOptionArrayInfo",
  "4": "ConfigPerfGradeItemOptionArrayInfo",
  "5": "ConfigPerfBoolItemOptionArrayInfo",
  "6": "ConfigPerfCombineItemOptionArrayInfo",
}
