//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigBattleFervorFactor: TypeIndexDefault = {
  "0": "ConfigBattleFervorFactor",
  "1": "ConfigBattleFervorFactor_ByTrigger",
  "2": "ConfigBattleFervorFactor_ByMonster",
}
