//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigJudgeNodeBase: TypeIndexDefault = {
  "0": "ConfigJudgeNodeBase",
  "1": "ConfigJudgeGroupEntityInView",
  "2": "ConfigJudgeCurrentTime",
  "3": "ConfigJudgeMoonOrSunInCamera",
  "4": "ConfigJudgeEntityInViewByEntityConfigID",
  "5": "ConfigJudgeAvatarElementType",
  "6": "ConfigJudgeAvatarWeaponType",
  "7": "ConfigJudgeAvatarFaceCamera",
  "8": "ConfigJudgeAvatarFaceTarget2D",
  "9": "ConfigJudgeAvatarAnimatorState",
  "10": "ConfigJudgeGroupEntityDirectionHasBlock",
  "11": "ConfigJudgeAvatarConfigID",
  "12": "ConfigJudgeNodeContainer",
  "13": "ConfigJudgeNodeContainerWithGroupEntityInfo",
}
