//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigGadgetPredicate: TypeIndexDefault = {
  "0": "ConfigGadgetPredicate",
  "1": "ConfigPredicateByTime",
  "2": "ConfigPredicateByPlatform",
  "3": "ConfigPredicateByInteract",
}
