//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigMove: TypeIndexDefault = {
  "0": "ConfigMove",
  "1": "ConfigSimpleMove",
  "2": "ConfigRigidbodyMove",
  "3": "ConfigFormulaicMove",
  "4": "ConfigVehicleMove",
  "5": "ConfigAnimatorMove",
  "6": "ConfigPlatformMove",
  "7": "ConfigScenePropAnimatorMove",
  "8": "ConfigWindmillMove",
  "9": "ConfigBulletMove",
  "10": "ConfigFollowMove",
  "11": "ConfigBoatMove",
  "12": "ConfigSkiffMove",
  "13": "ConfigNPCMove",
  "14": "ConfigLinerBulletMove",
  "15": "ConfigAnimationBulletMove",
  "16": "ConfigSurroundBulletMove",
  "17": "ConfigPinballBulletMove",
  "18": "ConfigParabolaBulletMove",
  "19": "ConfigFishingAimParabolaBulletMove",
  "20": "ConfigTrackBulletMove",
  "21": "ConfigItanoCircusBulletMove",
  "22": "ConfigMultiBulletMove",
  "23": "ConfigLinerParabolaBulletMove",
}
