//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigLocalGadgetCmd: TypeIndexDefault = {
  "0": "ConfigLocalGadgetCmd",
  "1": "ConfigLocalGadgetSetMaterialCmd",
}
