//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigBeHitBlendShake: TypeIndexDefault = {
  "0": "ConfigBeHitBlendShake",
  "1": "ConfigBeHitBlendShakeByAinmator",
}
