//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigCameraSplineBasePath: TypeIndexDefault = {
  "0": "ConfigCameraSplineBasePath",
  "1": "ConfigCameraSplineCameraPath",
  "2": "ConfigCameraSplineTargetPath",
}
