//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigGadgetStateAction: TypeIndexDefault = {
  "0": "ConfigGadgetStateAction",
  "1": "ConfigGadgetStateFireEffect",
  "2": "ConfigGadgetStateSetAnimTrigger",
  "3": "ConfigGadgetStateSetAnimInt",
  "4": "ConfigGadgetStateFireAISound",
  "5": "ConfigGadgetStateEnableGadgetIntee",
  "6": "ConfigGadgetStateEnableAction",
  "7": "ConfigGadgetStateDisableRadarHint",
  "8": "ConfigGadgetStateSendEffectTrigger",
}
