//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigGadgetUIBase: TypeIndexDefault = {
  "0": "ConfigGadgetUIBase",
  "1": "ConfigGadgetUIExtraItem",
  "2": "ConfigGadgetUI",
}
