import { TypeIndexDefault } from "./"

export const ConfigScenePoint: TypeIndexDefault = {
  "0": "ConfigScenePoint",
  "1": "SceneTransPoint",
  "2": "DungeonExit",
  "3": "DungeonWayPoint",
  "4": "DungeonSlipRevivePoint",
  "5": "DungeonQuitPoint",
  "6": "DungeonRewardPoint",
  "7": "PersonalSceneJumpPoint",
  "8": "SceneBuildingPoint",
  "9": "SceneVehicleSummonPoint",
  "10": "ConfigForceField",
  "11": "ConfigLocalEntity",
  "12": "ConfigLoadingDoor",
  "13": "VirtualTransPoint",
  "14": "DungeonEntry",
  "15": "ConfigConstForceField",
  "16": "ConfigRiseField",
  "17": "ConfigAirflowField",
  "18": "ConfigSpeedupField",
  "19": "ConfigDirectedForceField",
  "20": "ConfigLightCore",
  "21": "ConfigFireGrassAirflowField",
  "23": "ConfigCannonField",
  "24": "ConfigWindmill",
  "25": "ConfigLocalInteractEntity",
  "26": "ConfigLocalTrigger",
  "27": "ConfigFishpondScenePoint",
}
