//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigCameraSplineBaseTarget: TypeIndexDefault = {
  "0": "ConfigCameraSplineBaseTarget",
  "1": "ConfigCameraSplineCatmullTarget",
  "2": "ConfigCameraSplineBezierTarget",
}
