import { TypeIndexDefault } from "."

export const ConfigMove: TypeIndexDefault = {
  "0": "ConfigMove",
  "1": "ConfigSimpleMove",
  "2": "ConfigRigidbodyMove",
  "3": "ConfigMixinDriveMove",
  "4": "ConfigFormulaicMove",
  "5": "ConfigVehicleMove",
  "6": "ConfigAnimatorMove",
  "7": "ConfigPlatformMove",
  "9": "ConfigScenePropColliderMove",
  "10": "ConfigWindmillMove",
  "11": "ConfigBulletMove",
  "12": "ConfigFollowMove",
  "13": "ConfigBoatMove",
  "14": "ConfigSkiffMove",
  "15": "ConfigNPCMove",
  "16": "ConfigLinerBulletMove",
  "17": "ConfigAnimationBulletMove",
  "18": "ConfigScenePropAnimatorMove",
  "19": "ConfigSurroundBulletMove",
  "20": "ConfigPinballBulletMove",
  "21": "ConfigParabolaBulletMove",
  "22": "ConfigFishingAimParabolaBulletMove",
  "23": "ConfigTrackBulletMove",
  "24": "ConfigItanoCircusBulletMove",
  "25": "ConfigMultiBulletMove",
  "26": "ConfigLinerParabolaBulletMove",
  "27": "ConfigBoomerangBulletMove",
}
