//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigPerfItemBase: TypeIndexDefault = {
  "0": "ConfigPerfItemBase",
  "1": "ConfigPerfNumberItem",
  "2": "ConfigPerfNumberArrayItem",
  "3": "ConfigPerfStringKeyItem",
  "4": "ConfigPerfGradeItem",
  "5": "ConfigPerfBoolItem",
  "6": "ConfigPerfCombinedItem",
}
