//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigBaseAttackPattern: TypeIndexDefault = {
  "0": "ConfigBaseAttackPattern",
  "1": "ConfigSimpleAttackPattern",
  "2": "ConfigAttackUsePrefab",
  "3": "ConfigAttackTrail",
  "4": "ConfigAttackBox",
  "5": "ConfigAttackCircle",
  "6": "ConfigAttackSphere",
  "7": "ConfigAttackDoubleTrail",
}
