//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigCoopBaseNode: TypeIndexDefault = {
  "0": "ConfigCoopBaseNode",
  "1": "ConfigCoopTalkNode",
  "2": "ConfigCoopCondNode",
  "3": "ConfigCoopSelectNode",
  "4": "ConfigCoopActionNode",
  "5": "ConfigCoopEndNode",
}
