import { TypeIndexDefault } from "./"

export const ConfigBaseWidgetToy: TypeIndexDefault = {
  "0": "ConfigBaseWidgetToy",
  "1": "ConfigWidgetToyAnchorPoint",
  "2": "ConfigWidgetToyBonfire",
  "3": "ConfigWidgetToyLunchBox",
  "4": "ConfigWidgetToyClintDetector",
  "5": "ConfigWidgetToyOneoffGatherPointDetector",
  "6": "ConfigWidgetToyClintCollector",
  "7": "ConfigWidgetToyTreasureMapDetector",
  "9": "ConfigWidgetToyBlessingCamera",
  "10": "ConfigWidgetScanCamera",
  "11": "ConfigWidgetToyGadgetBuilder",
  "12": "ConfigWidgetToyMiracleRing",
  "13": "ConfigWidgetToyOpenPage",
  "14": "ConfigWidgetToyWaterSprite",
  "15": "ConfigWidgetToyTakePhoto",
  "16": "ConfigWidgetToyFeather",
  "17": "ConfigWidgetToyCreateGadgetBase",
  "18": "ConfigWidgetAddBuff",
  "19": "ConfigWidgetToyCamera",
  "20": "ConfigWidgetToyAbilityGroupGenerator",
  "21": "ConfigWidgetUseAttachAbilityGroup",
  "22": "ConfigWidgetUseAttachAbilityTrigger",
  "23": "ConfigWidgetLightStone",
  "25": "ConfigWidgetToyInstrument",
  "26": "ConfigWidgetToyAdeptiAbode",
  "27": "ConfigWidgetDigScanner",
  "28": "ConfigWidgetFireworksLauncher",
  "29": "ConfigWidgetRockBoardDetector",
  "30": "ConfigWidgetCaptureAnimal",
  "31": "ConfigWidgetToyCrystal",
  "32": "ConfigWidgetActivityGacha",
  "33": "ConfigWidgetAranaraController",
  "34": "ConfigWidgetToyHitTree",
  "35": "ConfigWidgetFishing",
}
