import { TypeIndexDefault } from "./"

export const ConfigAITacticBaseSetting: TypeIndexDefault = {
  "0": "ConfigAITacticBaseSetting",
  "1": "ConfigAIReturnToBornPosSetting",
  "2": "ConfigAIWanderSetting",
  "3": "ConfigAIFollowScriptedPathSetting",
  "4": "ConfigAIFollowServerRouteSetting",
  "5": "ConfigAIInvestigateSetting",
  "6": "ConfigAIReactActionPointSetting",
  "7": "ConfigAIPatrolFollowSetting",
  "8": "ConfigAICombatFollowMoveSetting",
  "9": "ConfigAIMeleeChargeSetting",
  "10": "ConfigAIFacingMoveSetting",
  "11": "ConfigAISurroundSetting",
  "12": "ConfigAIGroupSurroundSetting",
  "13": "ConfigAIFindBackSetting",
  "14": "ConfigAICombatFixedMoveSetting",
  "15": "ConfigAICrabMoveSetting",
  "16": "ConfigAIFleeSetting",
  "17": "ConfigAIFleeOnBlockAvatarLandingSetting",
  "18": "ConfigAISpacialChaseSetting",
  "19": "ConfigAISpacialProbeSetting",
  "20": "ConfigAISpacialAdjustSetting",
  "21": "ConfigAISpacialWanderSetting",
  "22": "ConfigAIBirdCirclingSetting",
  "23": "ConfigAIScriptedMoveToSetting",
  "24": "ConfigAILandingSetting",
  "25": "ConfigAIExtractionSetting",
  "26": "ConfigAIBrownianMotionSetting",
  "27": "ConfigAIFishingBitesBaitSetting",
  "28": "ConfigAIFishingPretendBitesSetting",
  "29": "ConfigAIFishingFleeSetting",
  "30": "ConfigAISpacialFacingMoveSetting",
}
