//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigVBaseMark: TypeIndexDefault = {
  "0": "ConfigVBaseMark",
  "1": "ConfigVMapMark",
  "2": "ConfigVCustomMapMark",
}
