//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigDialogGroup: TypeIndexDefault = {
  "0": "ConfigDialogGroup",
  "1": "ConfigFreeDialogGroup",
  "2": "ConfigNarratorDialogGroup",
  "3": "ConfigBlossomDialogGroup",
  "4": "ConfigActivityDialogGroup",
  "5": "ConfigCoopDialogGroup",
  "6": "ConfigGadgetDialogGroup",
  "7": "ConfigNpcOtherDialogGroup",
  "8": "ConfigCutsceneDialogGroup",
}
