//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigTalentMixin: TypeIndexDefault = {
  "0": "ConfigTalentMixin",
  "1": "AddAbility",
  "2": "ModifyAbility",
  "3": "UnlockTalentParam",
  "4": "UnlockControllerConditions",
  "5": "ModifySkillCD",
  "6": "ModifySkillCost",
  "7": "ModifySkillPoint",
  "8": "AddTalentExtraLevel",
}
