//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigLevelNpcBornPos: TypeIndexDefault = {
  "0": "ConfigLevelNpcBornPos",
  "1": "ConfigLevelNpcBornPosNoGroup",
}
