//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const ConfigBattleFervorUpdatePredicate: TypeIndexDefault = {
  "0": "ConfigBattleFervorUpdatePredicate",
  "1": "ConfigBattleFervorUpdatePredicate_FactorRange",
  "2": "ConfigBattleFervorUpdatePredicate_LocalAvatarInBattle",
}
