//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const SelectTargets: TypeIndexDefault = {
  "0": "SelectTargets",
  "1": "SelectTargetsByShape",
  "2": "SelectTargetsByEquipParts",
  "3": "SelectTargetsByChildren",
  "4": "SelectTargetsByChildrenEntityType",
  "5": "SelectTargetsByTag",
  "6": "SelectTargetsBySelfGroup",
  "7": "SelectTargetsByLCTrigger",
  "8": "SelectTargetsByLCTriggerAll",
}
