//Auto Generated by ConfigParser
import { TypeIndexDefault } from "./"

export const TemplateParam: TypeIndexDefault = {
  "0": "TemplateParam",
  "1": "TemplateParamFloat",
  "2": "TemplateParamInt32",
  "3": "TemplateParamString",
}
