import { basename } from "path"

import { FileType } from "./FileType"

interface ConfigEntry {
  className: string
  mode: FileType
  derivation: boolean
}

export default class ConfigResolver {
  private static ConfigMap: { [key: string]: ConfigEntry } = {
    "/Scene/Point/": { className: "ConfigScene", mode: FileType.Single, derivation: true },
    "/Scene/SceneNpcBorn/": { className: "ConfigLevelNpcBornPosNoGroup", mode: FileType.Single, derivation: true },
    "/Scene/SceneNpcBornNoGroup/": {
      className: "ConfigLevelNpcBornPosNoGroup",
      mode: FileType.Single,
      derivation: true,
    },
    "/Scene/LevelLayout/": { className: "ConfigLevelLayout", mode: FileType.Single, derivation: true },
    "/Scene/WorldArea/": { className: "ConfigWorldAreaLayout", mode: FileType.Single, derivation: true },
    "/Voice/Items/": { className: "ConfigExternalVoiceItem", mode: FileType.Dictionary, derivation: true },
    "/Voice/Lut/": { className: "ConfigExternalVoiceLookupItem", mode: FileType.DictionaryVuit, derivation: true },
    "/Voice/Emo/": { className: "ConfigExternalVoiceLookupItem", mode: FileType.Single, derivation: true },
    "/Talk/Activity/": { className: "ConfigActivityDialogGroup", mode: FileType.Single, derivation: true },
    "/Talk/ActivityGroup/": { className: "ConfigActivityTalkScheme", mode: FileType.Single, derivation: true },
    "/Talk/Blossom/": { className: "ConfigBlossomDialogGroup", mode: FileType.Single, derivation: true },
    "/Talk/BlossomGroup/": { className: "ConfigTalkScheme", mode: FileType.Single, derivation: true },
    "/Talk/Gadget/": { className: "ConfigGadgetDialogGroup", mode: FileType.Single, derivation: true },
    "/Talk/GadgetGroup/": { className: "ConfigGadgetTalkScheme", mode: FileType.Single, derivation: true },
    "/Talk/Npc/": { className: "ConfigNarratorDialogGroup", mode: FileType.Single, derivation: true },
    "/Talk/NpcOther/": { className: "ConfigNarratorDialogGroup", mode: FileType.Single, derivation: true },
    "/Talk/NpcGroup/": { className: "ConfigNpcTalkScheme", mode: FileType.Single, derivation: true },
    "/Talk/Coop/": { className: "ConfigCoopDialogGroup", mode: FileType.Single, derivation: true },
    "/Talk/FreeGroup/": { className: "ConfigFreeDialogGroup", mode: FileType.Single, derivation: true },
    "/Talk/Other/": { className: "ConfigDialogGroup", mode: FileType.Single, derivation: true },
    "/Talk/Quest/": { className: "ConfigDialogGroup", mode: FileType.Single, derivation: false },
    "/Music/Music/": { className: "ConfigMusic", mode: FileType.Single, derivation: true },
    "/Music/Songs/": { className: "ConfigSong", mode: FileType.List, derivation: true },
    "/Music/TransitionConditions/": { className: "ConfigMusicCondition", mode: FileType.List, derivation: true },
    "/LevelDesign/ActionPoints/": { className: "ConfigLevelActionPoint", mode: FileType.Single, derivation: true },
    "/LevelDesign/Gadgets/": { className: "ConfigLevelGadgetData", mode: FileType.Single, derivation: true },
    "/LevelDesign/Monsters/": { className: "ConfigLevelMonsterData", mode: FileType.Single, derivation: true },
    "/LevelDesign/Polygons/": { className: "ConfigLevelPolygons", mode: FileType.Single, derivation: true },
    "/LevelDesign/Routes/": { className: "ConfigLevelRoute", mode: FileType.Single, derivation: true },
    "/LevelDesign/SimplePolygons/": { className: "ConfigPolygonArea", mode: FileType.Single, derivation: true },
    "/LevelDesign/Meta/": { className: "ConfigLevelMeta", mode: FileType.Single, derivation: true },
    "/LevelDesign/DeathZone/": { className: "TODO", mode: FileType.Single, derivation: true }, //TODO
    "/HomeFurniture/Fishpond/": { className: "ConfigHomeFishpondSet", mode: FileType.Single, derivation: true },
    "/HomeFurniture/Fishtank/": { className: "ConfigHomeFishtankSet", mode: FileType.Single, derivation: true },
    "/HomeFurniture/HomeworldGroup/": {
      className: "ConfigHomeworldFurnitureSet",
      mode: FileType.Single,
      derivation: true,
    },
    "/RandomQuest/": { className: "ConfigRandomQuestGlobalScheme", mode: FileType.Single, derivation: true },
    "/Global/Embeded/TextMap/": { className: "ConfigTextMapLevel", mode: FileType.Single, derivation: true },
    "/Global/Embeded/UI/": { className: "ConfigUIGlobal", mode: FileType.Single, derivation: true },
    "/Global/GlobalValues/": { className: "ConfigGlobalValues", mode: FileType.Single, derivation: true },
    "/Global/Mark/": { className: "ConfigMarkGlobal", mode: FileType.Single, derivation: true },
    "/Global/GlobalData": { className: "ConfigModeStateMap", mode: FileType.Single, derivation: true },
    "/Global/Npc": { className: "TODO", mode: FileType.Single, derivation: true }, //TODO
    "/Audio/Ambience/": { className: "ConfigAudioAmbience", mode: FileType.Single, derivation: true },
    "/Audio/Area2DAmbience/": { className: "ConfigAudioArea2DAmbience", mode: FileType.List, derivation: true },
    "/Audio/Avatar/": { className: "ConfigAudioAvatar", mode: FileType.Single, derivation: true },
    "/Audio/AvatarMove/": { className: "ConfigAudioAvatarMove", mode: FileType.Single, derivation: true },
    "/Audio/AvatarSpeech/": { className: "ConfigAvatarSpeech", mode: FileType.Single, derivation: true },
    "/Audio/BaseMove/": { className: "ConfigAudioBaseMove", mode: FileType.Single, derivation: true },
    "/Audio/Camera/": { className: "ConfigAudioCamera", mode: FileType.Single, derivation: true },
    "/Audio/CityBlocks/": { className: "ConfigAudioCityBlocks", mode: FileType.Single, derivation: true },
    "/Audio/Combat/": { className: "ConfigAudioCombat", mode: FileType.Single, derivation: true },
    "/Audio/Dialog/": { className: "ConfigAudioDialog", mode: FileType.Single, derivation: true },
    "/Audio/EventCulling/": { className: "ConfigAudioEventCulling", mode: FileType.Single, derivation: true },
    "/Audio/Gadget/": { className: "ConfigAudioGadget", mode: FileType.Single, derivation: true },
    "/Audio/GameViewState/": { className: "ConfigAudioGameViewState", mode: FileType.Single, derivation: true },
    "/Audio/General/": { className: "ConfigAudioGeneral", mode: FileType.Single, derivation: true },
    "/Audio/Level/": { className: "ConfigAudioLevel", mode: FileType.Single, derivation: true },
    "/Audio/Listener/": { className: "ConfigAudioListener", mode: FileType.Single, derivation: true },
    "/Audio/MapInfo/": { className: "ConfigAudioMapInfo", mode: FileType.Single, derivation: true },
    "/Audio/Midi/": { className: "ConfigAudioMIDI", mode: FileType.Single, derivation: true },
    "/Audio/Music/": { className: "ConfigAudioMusic", mode: FileType.Single, derivation: true },
    "/Audio/MutualExclusion/": { className: "ConfigAudioMutualExclusion", mode: FileType.Single, derivation: true },
    "/Audio/Npc/": { className: "ConfigAudioNpc", mode: FileType.Single, derivation: true },
    "/Audio/Quest/": { className: "ConfigAudioQuest", mode: FileType.Single, derivation: true },
    "/Audio/Resource/": { className: "ConfigAudioResource", mode: FileType.Single, derivation: true },
    "/Audio/Setting/": { className: "ConfigAudioSetting", mode: FileType.Single, derivation: true },
    "/Audio/Spatial/": { className: "ConfigSpatialAudio", mode: FileType.Single, derivation: true },
    "/Audio/SurfaceType/": { className: "ConfigAudioSurfaceType", mode: FileType.Single, derivation: true },
    "/Audio/UI/": { className: "ConfigAudioUi", mode: FileType.Single, derivation: true },
    "/Audio/Weather/": { className: "ConfigAudioWeather", mode: FileType.Single, derivation: true },
    "/Ability/": { className: "ConfigAbility", mode: FileType.ListDictionary, derivation: true },
    "/AbilityActionChannel/": {
      className: "ConfigPlatformActionTokenChannel",
      mode: FileType.Single,
      derivation: true,
    },
    "/AbilityGroup/": { className: "ConfigAbilityGroup", mode: FileType.Dictionary, derivation: true },
    "/AbilityPath/": { className: "ConfigAbilityPath", mode: FileType.Single, derivation: true },
    "/AbilitySystem/": { className: "ConfigAbilitySystem", mode: FileType.Single, derivation: true },
    "/AnimPattern/": { className: "ConfigAnimPatternPath", mode: FileType.Single, derivation: true },
    "/AnimatorConfig/": { className: "ConfigAnimator", mode: FileType.Single, derivation: true },
    "/AttachData/": { className: "ConfigAttachmentData", mode: FileType.Single, derivation: true },
    "/AudioEmitter/": { className: "ConfigAudioEmitter", mode: FileType.Single, derivation: true },
    "/Avatar/": { className: "ConfigAvatar", mode: FileType.Single, derivation: true },
    "/Boundary/": { className: "ConfigBoundary", mode: FileType.Dictionary, derivation: true },
    "/Climate/": { className: "ConfigClimate", mode: FileType.Single, derivation: true },
    "/CodexQuest/": { className: "ConfigCodexQuest", mode: FileType.Single, derivation: true },
    "/Common/ConfigGlobalCombat": { className: "ConfigGlobalCombat", mode: FileType.Single, derivation: true },
    "/Component/LCBaseIntee": { className: "ConfigLCBaseIntee", mode: FileType.Single, derivation: true },
    "/Component/LCGadgetIntee": { className: "ConfigLCGadgetIntee", mode: FileType.Single, derivation: true },
    "/Coop/": { className: "ConfigMainCoopGroup", mode: FileType.Single, derivation: true },
    "/CrowdGroupInfos/": { className: "ConfigCrowdGroupInfo", mode: FileType.List, derivation: true },
    "/CrowdSpawnInfos/": { className: "ConfigCrowdSpawnInfos", mode: FileType.Single, derivation: true },
    "/Cutscene/": { className: "ConfigCutsceneIndex", mode: FileType.Single, derivation: true },
    "/CustomLevelDungeon/": { className: "ConfigCustomLevelDungeon", mode: FileType.Single, derivation: true },
    "/DynamicAbilityPreload/": {
      className: "ConfigDynamicAbilityPreload",
      mode: FileType.Dictionary,
      derivation: true,
    },
    "/Effect/": { className: "ConfigEffectData", mode: FileType.Single, derivation: true },
    "/EmojiBubble/": { className: "ConfigEmojiBubbleData", mode: FileType.Dictionary, derivation: true },
    "/EntityBan/": { className: "ConfigEntityBanData", mode: FileType.Single, derivation: true },
    "/EntityReuse/": { className: "ConfigEntityReuse", mode: FileType.Single, derivation: true },
    "/Fashion/AvatarCostume/": { className: "ConfigCostumeInfo", mode: FileType.Dictionary, derivation: true },
    "/Fashion/Flycloak/": { className: "ConfigFlycloakFashion", mode: FileType.Single, derivation: true },
    "/Gadget/": { className: "ConfigGadget", mode: FileType.Dictionary, derivation: true },
    "/GadgetPath/": { className: "ConfigGadgetPath", mode: FileType.Single, derivation: true },
    "/Goddess/": { className: "ConfigResonanceCutSceneMap", mode: FileType.Single, derivation: true },
    "/GraphicsSetting/": { className: "ConfigPlatformGrahpicsSetting", mode: FileType.Single, derivation: true },
    "/Guide/": { className: "ConfigGuideTask", mode: FileType.Dictionary, derivation: true },
    "/GuideContextList/": { className: "ConfigGuideContextList", mode: FileType.Dictionary, derivation: true },
    "/Homeworld/": { className: "ConfigHomePlaceColPath", mode: FileType.Single, derivation: true },
    "/HomeworldDefaultSave/": { className: "ConfigHomeworldDefaultSave", mode: FileType.Single, derivation: true },
    "/HomeworldFurnitureSuit/": { className: "ConfigHomeworldFurnitureSet", mode: FileType.Single, derivation: true },
    "/IndexDic/": { className: "ConfigIndexDic", mode: FileType.DictionaryVuitVuit, derivation: true },
    "/Indicator/": { className: "ConfigUIIndicator", mode: FileType.Dictionary, derivation: true },
    "/InterAction/": { className: "ConfigInterContainer", mode: FileType.Single, derivation: true },
    "/KeyboardLayout/": { className: "ConfigKeyboardLayout", mode: FileType.Single, derivation: true },
    "/LanguageSetting/": { className: "ConfigLanguageSetting", mode: FileType.Single, derivation: true },
    "/LevelEntity/": { className: "ConfigLevelEntity", mode: FileType.Dictionary, derivation: true },
    "/LogoPage/": { className: "ConfigLogoPageSetting", mode: FileType.Single, derivation: true },
    "/LuaHackConfig/": { className: "ConfigLuaHack", mode: FileType.Single, derivation: true },
    "/MainPageDisableInfo/": { className: "ConfigMainPageDisableInfo", mode: FileType.Dictionary, derivation: true },
    "/Mark/": { className: "ConfigMapGlobal", mode: FileType.Single, derivation: true },
    "/Monster/": { className: "ConfigMonster", mode: FileType.Single, derivation: true },
    "/MultiPlatformUIData/": { className: "ConfigMutiPlatformUIData", mode: FileType.Single, derivation: true },
    "/MusicGame/": { className: "ConfigMusicGame", mode: FileType.Single, derivation: true },
    "/MusicGameCamera/": { className: "ConfigMusicGameCamera", mode: FileType.Single, derivation: true },
    "/Npc/": { className: "ConfigNpc", mode: FileType.Single, derivation: true },
    "/PlayMode/": { className: "ConfigModeStateMap", mode: FileType.Single, derivation: true },
    "/Preload/": { className: "ConfigFullPreload", mode: FileType.Single, derivation: true },
    "/PS4/": { className: "ConfigPS4TRC", mode: FileType.Single, derivation: true },
    "/Quest/": { className: "ConfigMainQuestScheme", mode: FileType.Single, derivation: true },
    "/QuestBrief/": { className: "ConfigMainQuestBrief", mode: FileType.Single, derivation: true },
    "/SCameraMove/": { className: "ConfigCameraMove", mode: FileType.Dictionary, derivation: true },
    "/Schedule/": { className: "ConfigJobData", mode: FileType.Single, derivation: true },
    "/Shape/": { className: "ConfigBaseShape", mode: FileType.Dictionary, derivation: true },
    "/Skin/": { className: "ConfigSkin", mode: FileType.Dictionary, derivation: true },
    "/SoundBank/": { className: "ConfigSoundBankLookup", mode: FileType.Single, derivation: true },
    "/StageAudio/": { className: "ConfigAudioStageEvents", mode: FileType.Single, derivation: true },
    "/StreamPolygon/": { className: "ConfigLevelPolygon", mode: FileType.Single, derivation: true },
    "/Talent/": { className: "ConfigTalentMixin", mode: FileType.DictionaryList, derivation: true },
    "/Tile/": { className: "ConfigTile", mode: FileType.List, derivation: true },
    "/UI/": { className: "ConfigUI", mode: FileType.Single, derivation: true },
    "/Widget/": { className: "ConfigWidget", mode: FileType.Single, derivation: true },
    "/WidgetNew/": { className: "ConfigMainWidgetToy", mode: FileType.Single, derivation: true },
    "/PhotographCheck/": { className: "ConfigPhotographCheck", mode: FileType.Single, derivation: true },
    "/CrowdTextureHash/": { className: "ConfigCrowdTextureHash", mode: FileType.Single, derivation: true },
    "/ResourceCollection/": { className: "ConfigResourceCollection", mode: FileType.Single, derivation: true },
    "/GlobalPerf/": { className: "ConfigPlatformPerfSetting", mode: FileType.Single, derivation: true },
    "/Device/": { className: "ConfigDevice", mode: FileType.Single, derivation: true },
    "/HDMesh/": { className: "ConfigHDMesh", mode: FileType.Single, derivation: true },
    "/RegionPerf/": { className: "ConfigRegionPerf", mode: FileType.List, derivation: true },
    "/QTE/": { className: "ConfigQTEStepNode", mode: FileType.Single, derivation: true },
  }

  static resolve(path: string): ConfigEntry {
    const config = Object.entries(ConfigResolver.ConfigMap).find(([key]) => path.includes(key))?.[1]

    if (!config || config.className === null) {
      const fileName = basename(path)
      if (fileName.endsWith("Data"))
        return { className: fileName.slice(0, -4), mode: FileType.Packed, derivation: false }
      if (path.includes("TextMap")) return { className: "", mode: FileType.TextMap, derivation: false }
    }

    return config || { className: null, mode: FileType.Single, derivation: false }
  }
}
