//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AbilityOverrideParamConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    paramName: "string",
    paramValue: "float",
  },
}
