//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AbilityStateResistanceByIDExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    abilityStates: "AbilityState[]",
  },
}
