//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivitySalesmanRewardMatchConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    rewardID: "vuint",
    ReoureceType: "RewardResourceType",
    boxNameTextMapHash: "vuint",
  },
}
