//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivityShopSheetCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "ActivityShopSheetCondType",
    param: "vuint[]",
  },
}
