//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivityChessCardExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    ID: "vuint",
    number: "vuint",
    tag: "ChessCardTag",
    needChessLevel: "vuint",
    cardNameTextMapHash: "vuint",
    descTextMapHash: "vuint",
    extraDescTextMapHash: "vuint",
    extraDesc2TextMapHash: "vuint",
    descParamList: "float[][]",
    descParamSuperpositionList: "bool[]",
    isDisused: "bool",
    cardNumericalModificationType: "ChessCardNumericalModificationType",
    cardNumericalModificationMode: "ChessCardNumericalModificationMode",
    cardNumericalModificationValue: "float",
    costPoints: "vuint",
    cardType: "ChessCardType",
    cardQualityType: "ChessCardQualityType",
    cardCount: "vuint",
    effect: "ChessCardEffect",
    curseWeight: "vuint",
    isCanAttachCurse: "bool",
    isRemoveOnPick: "bool",
    isShowOnPick: "bool",
    extraEffectList: "ChessCardEffect[]",
  },
}
