//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivityPhotographExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    activityId: "vuint",
    photoPosIdList: "vuint[]",
    photoUseableWidgetList: "vuint[]",
  },
}
