//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivityDeliveryExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    scheduleId: "vuint",
    dailyConfigIdList: "vuint[]",
    needPlayerLevel: "vuint",
  },
}
