//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivityGachaStageTextExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    stageId: "vuint",
    stageTitleTextMapHash: "vuint",
    stageDesc1TextMapHash: "vuint",
    stageDesc2TextMapHash: "vuint",
    stageDesc3TextMapHash: "vuint",
    questTipsTextMapHash: "vuint",
  },
}
