//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivitySumoMonsterPreview: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    boss: "string",
    normal: "string",
  },
}
