//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivityBannerExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    activityId: "vuint",
    bannerType: "ActivityBannerType",
    rewardPreviewId: "vuint",
    jsonConfigName: "string",
    prefabPath: "string",
    showDesc: "bool",
    descTextMapHash: "vuint",
  },
}
