//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivityMistTrialLevelFactorExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    Id: "vuint",
    param: "string[]",
    factorRowTextTextMapHash: "vuint",
    entryShowTextTextMapHash: "vuint",
    inGameShowTextTextMapHash: "vuint",
  },
}
