//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivityDeliveryWatcherDataConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: "WatcherConfig",
  Fields: {},
}
