//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivitySkillExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    skillTarget: "ActivitySkillTarget",
    abilityName: "string",
    globalValueKey: "string",
    energyMin: "vuint",
    energyMax: "vuint",
    cdTime: "float",
    guideTime: "float",
    skillIcon: "string",
    guideKey: "string[]",
    guideOpenState: "OpenStateType",
    unableTextTextMapHash: "vuint",
    channelTextTextMapHash: "vuint",
    interruptTextTextMapHash: "vuint",
  },
}
