//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivitySpiceFoodExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    normalFoodId: "vuint",
    specialFoodId: "vuint",
    recipeMatId: "vuint",
    sourceDescTextMapHash: "vuint",
  },
}
