import { ConfigDefault } from "../"

export const ActivityMuqadasPotionExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    activityId: "vuint",
    levelTimeLimit: "vuint",
    energyLimit: "vuint",
    skillNumLimit: "vuint",
    initSkillNum: "vuint",
    onceCaptureLimit: "vuint",
    MDBKAGHPDOA: "vuint",
    BNPIAEPKPMC: "float",
    NOHNLOALKDH: "float",
    MDDAIAIJILP: "vuint",
    DGNELBIHMHI: "float",
    LLJFILEECIO: "string",
    OIHJMIHJMGE: "string",
    JFPFDCJBGHC: "string",
    JAGHBKEAPPN: "string",
    HAPPKGIILNP: "string",
    CJIIJFOJJGG: "string",
    MJAJGCELONP: "string",
    FNPOKFAKJLK: "string",
    JDOODKAJILM: "float",
    KJBHAFFEHDB: "float",
    DMFABEAGGAE: "float",
    OOIIBIOBFJG: "vuint",
  },
}
