//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivityDeliveryDailyExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    dailyConfigId: "vuint",
    deliveryQuestConfig: "DeliveryQuestConfig[]",
    taskDesc: "vuint[]",
    dailyRewardId: "vuint",
  },
}
