//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivityShopSheetExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    isAheadPreview: "bool",
    condComb: "LogicType",
    SheetNameTextMapHash: "vuint",
    cond: "ActivityShopSheetCond[]",
    sortLevel: "vuint[]",
  },
}
