//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ActivityMistTrialAvatarDataExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    Id: "vuint",
    scheduleId: "vuint",
    trialAvatarId: "vuint",
  },
}
