//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AsterMidExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    camp_vec: "vuint[]",
  },
}
