import { ConfigDefault } from "../"

export const AudioSceneConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    sceneId: "vuint",
    DLLAMHKGEBB: "vuint",
    BBPDEHAAJFM: "vuint",
    OJCFPIKCJJG: "float",
    GNAIAFIDMGD: "vint",
    MCGEEGLEAKI: "float",
    CDJIFPIHAEN: "float",
    NENNDKIACEP: "float",
    HICFILAONMC: "float",
    MMNAHALKJNL: "float",
    IEKLJGDOIGF: "float",
    NCDHHDECJIK: "float",
    HOHMBNPBNFP: "float",
    ADJEIKGJPDD: "float",
    MOMBKEGNAPP: "float",
    FFLHKFGKNDB: "float",
    BEGGPNGHNIA: "float",
    MBPCMFMPKAF: "float",
    KFAIABIPKNH: "float",
    NJEBFPFKCMC: "float",
    KBMAPNEBHGD: "float",
    FKMEMDAGECJ: "float",
    OBJMJMMHMMM: "float",
    IFDEDHMAKPG: "float",
    JKEJKNHGMIO: "float",
    MFPNJMEOHNB: "float",
    KDBNNDLPEHE: "float",
    PGJJMKINBPE: "float",
    GCDGJGLDBIF: "float",
  },
}
