//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AvatarHeroEntityExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    avatarId: "vuint",
    prefabPathHashSuffix: "vuint",
    prefabPathHashPre: "byte",
    animatorConfigPathHashSuffix: "vuint",
    animatorConfigPathHashPre: "byte",
  },
}
