import { ConfigDefault } from "../"

export const AvatarSkillExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    nameTextMapHash: "vuint",
    abilityName: "string",
    descTextMapHash: "vuint",
    skillIcon: "string",
    isRanged: "bool",
    cdTime: "float",
    ignoreCDMinusRatio: "bool",
    costStamina: "float",
    costElemType: "ElementType",
    costElemVal: "float",
    maxChargeNum: "vint",
    triggerID: "vint",
    lockShape: "string",
    lockWeightParams: "float[]",
    isAttackCameraLock: "bool",
    dragType: "SkillDrag",
    showIconArrow: "bool",
    needMonitor: "MonitorType",
    defaultLocked: "bool",
    buffIcon: "string",
    proudSkillGroupId: "vuint",
    globalValueKey: "string",
    energyMin: "float",
    forceCanDoSkill: "bool",
    cdSlot: "vuint",
    needStore: "bool",
    shareCDID: "vuint",
    Unk3852_sus: "vuint",
  },
}
