//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AvatarLevelExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    level: "vuint",
    exp: "vuint",
    smallTalentPoint: "vuint",
  },
}
