//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const AvatarReplaceCostumeExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    avatarId: "vuint",
    replace_costume_id: "vuint",
  },
}
