//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BartenderEventExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    effectType: "BartenderEffectType",
    miscId: "vuint",
    effectName: "string",
  },
}
