//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BattlePassRewardExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    indexId: "vuint",
    level: "vuint",
    freeRewardIdList: "vuint[]",
    paidRewardIdList: "vuint[]",
    showUp: "bool",
  },
}
