//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BattlePassLevelExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    level: "vuint",
    levelUpNeedPoint: "vuint",
  },
}
