//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BlessingPicUpConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    prob: "vuint",
  },
}
