//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BlitzRushExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    activityId: "vuint",
    contentDuration: "vuint",
    dungeonId: "vuint",
    dungeonEntryId: "vuint",
    dungeonRewardId: "vuint",
    prePreQuestID: "vuint",
    preQuestID: "vuint[]",
    rewardPreview: "vuint",
    hideOathEntrance: "bool",
  },
}
