//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BlockLimit: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    blockId: "vuint",
    count: "vuint",
  },
}
