//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BlossomSectionOrderExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    cityId: "vuint",
    sectionId: "vuint",
    order: "vuint",
  },
}
