//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BlossomOpenExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    cityId: "vuint",
    openLevel: "vuint",
  },
}
