//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BlossomReviseExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    grade: "vuint[]",
  },
}
