//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BlossomRewardExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    drop_id: "vuint",
    preview_reward: "vuint",
  },
}
