//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BlossomRefreshCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "BlossomRefreshCondType",
    param: "vuint[]",
  },
}
