//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BonusTreasureSolutionExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    show_imageHashSuffix: "vuint",
    show_imageHashPre: "byte",
    solution: "vuint[]",
  },
}
