//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BookSuitExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    suitNameTextMapHash: "vuint",
  },
}
