//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BoredMonsterConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    weight: "vuint",
    id: "vuint",
  },
}
