//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BounceConjuringItemExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    titleTextMapHash: "vuint",
    descTextMapHash: "vuint",
    bgIconHashSuffix: "vuint",
    bgIconHashPre: "byte",
  },
}
