//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const BuffIconExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    buffID: "vint",
    icon: "string",
    mutexType: "vint",
  },
}
