//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CaptureTagConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    captureType: "vuint",
    dropID: "vuint",
    itemID: "vuint",
  },
}
