//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ChannellerSlabLoopDungeonPreviewExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    activityId: "vuint",
    titleTextMapHash: "vuint",
    entryDescTextMapHash: "vuint",
    descTextMapHash: "vuint",
    openDay: "vuint",
    pointID: "vuint",
  },
}
