//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ChannellerSlabLoopDungeonRewardExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    scoreGrade: "vuint",
    rewardID: "vuint",
  },
}
