//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ChannellerSlabChapterExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    chapterId: "vuint",
    openDay: "vuint",
    titleTextMapHash: "vuint",
    preQuest: "vuint",
  },
}
