//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ChargeBarStyleExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    iconName: "string",
    fillEffectType: "ChargeFillEffect",
  },
}
