//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ComboConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    comboUpLimit: "vuint",
    rate: "float",
  },
}
