//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConfigHomeGather: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    homeGatherID: "vuint",
    bundleID: "vuint",
    dropID: "vuint",
    weight: "vuint",
  },
}
