//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ConstValueExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    name: "ConstValueType",
    value: "string[]",
  },
}
