//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CoolDownInfo: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    coolDownTime: "float",
    token: "vuint",
  },
}
