//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CoopCGExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    chapterId: "vuint",
    unlockPointId: "vuint",
    cgType: "CoopCGType",
    unlockCond: "CoopCondConfig[]",
    showImageHashSuffix: "vuint",
    showImageHashPre: "byte",
    showImageSmallHashSuffix: "vuint",
    showImageSmallHashPre: "byte",
    cgNameTextMapHash: "vuint",
    cgDesTextMapHash: "vuint",
    sortId: "vuint",
  },
}
