//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CoopCondConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    condType: "CoopTaskCondType",
    args: "vuint[]",
  },
}
