//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CustomGadgetSlotGroup: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    slotIdentifier: "string",
    slotList: "vuint[]",
  },
}
