//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CustomLevelUIConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    configId: "vuint",
    openDay: "vuint",
    watcherIdList: "vuint[]",
    levelInfo: "vuint[]",
  },
}
