//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CustomLevelTagSortConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    configId: "vuint",
    color: "string",
    endColor: "string",
  },
}
