//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CustomLevelDungeonConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    dungeonID: "vuint",
    order: "vuint",
    jsonPath: "string",
    mapPrefabPath: "string",
    mapScenePicHashSuffix: "vuint",
    mapScenePicHashPre: "byte",
    dataPicHashSuffix: "vuint",
    dataPicHashPre: "byte",
    roomNum: "vuint",
    roomNameFormatTextMapHash: "vuint",
    corridors: "string",
    countBrickList: "vuint[]",
  },
}
