//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const CutsceneExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    path: "string",
  },
}
