//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DailyTaskDropConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    drop_id: "vuint",
    preview_reward_id: "vuint",
  },
}
