//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DeliveryQuestConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    parentQuestId: "vuint",
    deliveryQuestId: "vuint",
    startQuestId: "vuint",
    talkQuestId: "vuint",
    watcherId: "vuint[]",
    itemId: "vuint",
  },
}
