//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DigOverAllExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    activityID: "vuint",
    duration: "vuint",
    questUnlockID: "vuint",
    questID: "vuint",
    stageUnlockID: "vuint",
    rewardPreviewId: "vuint",
    endQuestShowCond: "vuint",
    endQuestFinishCond: "vuint",
    endQuestID: "vuint",
  },
}
