//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DocumentExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    titleTextMapHash: "vuint",
    contentLocalizedId: "vuint",
    previewPath: "string",
    documentType: "DocumentType",
    videoPath: "string",
    subtitleID: "vuint",
  },
}
