//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DraftTransferConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    group_id: "vuint",
    config_id: "vuint",
  },
}
