//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DragonSpineMissionFinishConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "DragonSpineMissionFinishExecType",
    param: "string[]",
  },
}
