//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DungeonCondConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    condType: "DungeonCondType",
    param: "vint[]",
  },
}
