//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DungeonList: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    dungeonList: "vuint[]",
  },
}
