//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DungeonEntryExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    sceneId: "vuint",
    dungeon_entry_id: "vuint",
    type: "DungunEntryType",
    isShowInAdvHandbook: "bool",
    descTextMapHash: "vuint",
    cooldown_tips_dungeon_id: "vuint[]",
    is_default_open: "bool",
    is_daily_refresh: "bool",
    cond_comb: "LogicType",
    satisfied_cond: "DungeonEntrySatisfiedCond[]",
    pic_path: "string",
    system_open_ui_id: "vuint",
    reward_data_id: "vuint",
    description_cycle_reward_list: "vuint[][]",
  },
}
