//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const DungeonChallengeConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    targetTextTemplateTextMapHash: "vuint",
    subTargetTextTemplateTextMapHash: "vuint",
    progressTextTemplateTextMapHash: "vuint",
    subProgressTextTemplateTextMapHash: "vuint",
    iconPath: "string",
    challenge_type: "ChallengeType",
    isForwardTiming: "bool",
    recordType: "ChallengeRecordType",
    noSuccessHint: "bool",
    noFailHint: "bool",
    noPauseHint: "bool",
    interruptButtonType: "InterruptButtonType",
    isTransBackWhenInterrupt: "bool",
    isSuccessWhenNotSettled: "bool",
    isBlockTopTimer: "bool",
    subChallengeFadeOutRule: "SubChallengeFadeOutType",
    subChallengeFadeOutDelayTime: "float",
    subChallengeBannerRule: "SubChallengeBannerType",
    activitySkillID: "vuint",
    teamAbilityGroupList: "string[]",
  },
}
