//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EffigyChallengeExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    dayIndex: "vuint",
    dungeonId: "vuint",
    prefab: "string",
    titleTextMapHash: "vuint",
    contentTextMapHash: "vuint",
    limitingConditionVec: "vuint[]",
    upAvatarVec: "vuint[]",
    firstPassRewardId: "vuint",
  },
}
