//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ElementCoeffExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    level: "vuint",
    crashCo: "float",
    elementLevelCo: "float",
    playerElementLevelCo: "float",
    playerShieldLevelCo: "float",
  },
}
