//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EmojiDataExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    setID: "vuint",
    order: "vuint",
    contentTextMapHash: "vuint",
    icon: "string",
  },
}
