//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EndureTemplateExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "EndureType",
    gaugeLength: "float",
    waneSpeed: "float",
    recoverTime: "float",
    endurance: "float",
  },
}
