//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EntityPropPerMpConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    propType: "FightPropType",
    propValueVec: "float[]",
  },
}
