//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EntityExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    nameTextMapHash: "vuint",
    prefabPathHashSuffix: "vuint",
    prefabPathHashPre: "byte",
    prefabPathRemoteHashSuffix: "vuint",
    prefabPathRemoteHashPre: "byte",
    controllerPathHashSuffix: "vuint",
    controllerPathHashPre: "byte",
    controllerPathRemoteHashSuffix: "vuint",
    controllerPathRemoteHashPre: "byte",
    campID: "vuint",
    LODPatternName: "string",
  },
}
