//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const EnvironmentWeightType: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    animalId: "vuint",
    entityType: "EntityType",
    weight: "vuint",
    aliveHourMap: "map<vuint,vuint>",
  },
}
