//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ExpeditionOpenCondition: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "ExpeditionOpenCondType",
    para: "vuint",
    para2: "vuint",
  },
}
