//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ExpeditionBonusExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    avatarLevel: "vuint",
    probability: "float",
  },
}
