//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ExpeditionReward: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    htime: "vuint",
    reward_drop_id: "vuint",
    rewardPreview: "vuint",
  },
}
