//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ExpeditionDataExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    ID: "vuint",
    nameTextMapHash: "vuint",
    city_id: "vuint",
    open_condition_vec: "ExpeditionOpenCondition[]",
    time_reward_vec: "ExpeditionReward[]",
    descriptionTextMapHash: "vuint",
    picture: "string",
    posX: "float",
    posY: "float",
  },
}
