//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FettersExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: "FetterConfig",
  Fields: {
    type: "vuint",
    isHiden: "bool",
    hideCostumeList: "vuint[]",
    showCostumeList: "vuint[]",
    tips: "vuint[]",
    voice_titleTextMapHash: "vuint",
    voice_file: "string",
    voice_file_textTextMapHash: "vuint",
    voice_title_lockedTextMapHash: "vuint",
  },
}
