//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FetterConditionConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    condType: "FetterCondType",
    paramList: "vuint[]",
  },
}
