//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FetterConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    fetter_id: "vuint",
    avatarId: "vuint",
    openConds: "FetterConditionConfig[]",
    finishConds: "FetterConditionConfig[]",
  },
}
