//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FightPropGrowConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "FightPropType",
    grow_curve: "GrowCurveType",
  },
}
