//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FireworksReformParamConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "FireworksReformParamType",
    standardValue: "vint",
    isCanReform: "bool",
    valueRange: "vint[]",
  },
}
