//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FireElementAdditionConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    range: "vuint[]",
    ratio: "vuint",
  },
}
