//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FishStockLimit: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    stockType: "FishStockType",
    minNum: "vuint",
    maxNum: "vuint",
  },
}
