//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FishBaitFeature: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    featureTag: "vuint",
    weight: "float",
    bonusRange: "float",
  },
}
