//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FleurFairBuffEnergyStatExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    galleryId: "vuint",
    statParam: "string",
    priority: "vuint",
    titleTextMapHash: "vuint",
  },
}
