//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FlightDailyInfo: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    watcher: "vuint",
  },
}
