//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FlightDailyPointFactor: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    time_factor: "vuint",
    gold_factor: "vuint",
  },
}
