//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const FlightActivityDayExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    pos: "float[]",
  },
}
