import { ConfigDefault } from "../"

export const FungusBaseExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    activityId: "vuint",
    LHLNGEMCLHN: "vuint",
    FMBAFKAJPAD: "vuint",
    LCAFCIFHIKN: "vuint",
    JKKHCDCILCB: "vuint",
    IPPAHOIJOIK: "vuint",
    DLCGGPKMOFC: "vuint",
    GNDEFDHIBNH: "string",
    KNIPFBJOJHO: "string[]",
    LFMOCKDCNAH: "string",
    OCFAOIBODEP: "vuint",
    DJCMCCCDILB: "vuint",
    HJNLNMDPAPK: "vuint[]",
    PEOCIFHLNBI: "vuint[]",
    CIMOHCCDKLH: "vint",
    OOLLNFEJAMB: "vuint",
    DCBFHIEGHCA: "vuint",
    AJJFJFLHDDC: "vuint",
    BAMJGCKLFFL: "vuint",
    MBKPAKDOLED: "vuint",
    AAFDGPFLFCM: "vuint",
    IIEAJLNIGEE: "vuint",
    CCCNJLEHGCE: "vuint",
    BNEAIDIDJFH: "vuint",
    FDALMPDLBFP: "vuint",
    GGMMCDDPEDH: "vuint",
    JADFBCPGGKA: "vuint",
    NALFGONNKHC: "vuint",
  },
}
