import { ConfigDefault } from "../"

export const FungusTrainingDungeonExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    dungeonId: "vuint",
    DHDMMBHPJFC: "vuint",
    trainingType: "FungusTrainingDungeonType",
    unlockDay: "vuint",
    EDHDIIGNPGB: "vuint",
    galleryId: "vuint",
    PEOJPKNMDCH: "vuint[]",
    CJCHNOGFFDP: "vuint[]",
    JEEOAHEBBKJ: "vuint",
    AOKCEADFNAL: "vuint",
    INMPHOCCLMB: "vuint",
    CGKCADMCCAO: "vuint[]",
    JANCIDJKFOG: "vuint",
    baseScore: "float",
    OLICKNPNIFP: "float",
    MJHHINIADHA: "float",
    DDAOODALLFL: "float",
    IBJLLAKAICJ: "float",
    watcherIds: "vuint[]",
    BADHACKNEDA: "vuint",
    AAALFDNAKFB: "vuint",
    NBPCCJLPIOO: "vuint",
    MHNCGBJCGDI: "vuint",
    ADBDDHHHPDD: "vuint[]",
    KJOJEBMCIEC: "vuint",
  },
}
