//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const GadgetInteractCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    condType: "InteractCondType",
    param: "string[]",
  },
}
