//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const GadgetInteractActionConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    actionType: "InteractActionType",
    param: "vuint[]",
  },
}
