//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const GatherExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    area_id: "vuint",
    pointType: "vuint",
    gadgetId: "vuint",
    itemId: "vuint",
    extraItemIdVec: "vuint[]",
    pointLocation: "PointLocation",
    cd: "vuint",
    priority: "vuint",
    refreshId: "vuint",
    blockLimits: "BlockLimit[]",
    init_disable_interact: "bool",
    isForbidGuest: "bool",
    saveType: "GatherSaveType",
    isForbidMpMode: "bool",
  },
}
