//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const GrowCurveInfo: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "GrowCurveType",
    arith: "ArithType",
    value: "float",
  },
}
