//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const H5ActivityCondConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "H5ActivityCondType",
    paramStr: "string",
  },
}
