//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const HandbookQuestGuideShowCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "HandbookQuestGuideShowCondType",
    param: "vuint[]",
  },
}
