//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const HideAndSeekMatchExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: "MatchLimitExcelConfig",
  Fields: {
    titleTextMapHash: "vuint",
    unlockTipsTextMapHash: "vuint",
    unlockTips2TextMapHash: "vuint",
    unlockTips3TextMapHash: "vuint",
    dscTextMapHash: "vuint",
    mapIconPathHashSuffix: "vuint",
    mapIconPathHashPre: "byte",
    mapSmallIconPathHashSuffix: "vuint",
    mapSmallIconPathHashPre: "byte",
    sceneId: "vuint",
    groupId: "vuint",
    transportPointList: "vuint[]",
    durationList: "vuint[]",
    galleryID: "vuint",
  },
}
