//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const HideAndSeekAvatarSDExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    avatarId: "vuint",
    descTextMapHash: "vuint",
  },
}
