//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const HomeWorldLimitShopCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    condition: "HomeWorldLimitShopCondType",
    conditionParam: "vuint[]",
  },
}
