//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const HomeWorldExtraFurnitureExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    furnitureID: "vuint",
    extraData: "string[]",
  },
}
