//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const HomeWorldLeastShopExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    level: "vuint",
    poolID: "vuint",
    count: "vuint",
  },
}
