//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const HomeWorldAreaComfortExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    configID: "vuint",
    sceneID: "vuint",
    areaID: "vuint",
    areaType: "HomeWorldAreaType",
    nameTextMapHash: "vuint",
    maxComfort: "vuint",
    safePointStr: "string",
    lowLoadLimit: "vuint",
    middleLoadLimit: "vuint",
    highLoadLimit: "vuint",
    areaCenterPos: "float[]",
    areaCenterRot: "float[]",
  },
}
