//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const HomeWorldServerGadgetExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    furnitureId: "vuint",
    serverGadgetId: "vuint",
  },
}
