//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const HuntingClueTextExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    clueTextId: "vuint",
    reminderIdList: "vuint[]",
  },
}
