//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const HuntingClueGatherExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    configId: "vuint",
    gatherId: "vuint",
    gatherGroupId: "vuint",
    isClueGather: "bool",
  },
}
