//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IdCountStrConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    count: "string",
  },
}
