//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IdCountConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    count: "vuint",
  },
}
