//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IrodoriPoetryScanConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    indexIdList: "vuint[]",
    lineId: "vuint",
  },
}
