//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IrodoriChessMapPointExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    ID: "vuint",
    coordX: "float",
    coordY: "float",
  },
}
