//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IrodoriPoetryLineExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    ID: "vuint",
    contentTextMapHash: "vuint",
    var: "vuint",
  },
}
