//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IrodoriQuestExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    Id: "vuint",
    questId: "vuint",
    mainQuestIds: "vuint[]",
    questType: "LunaRiteQuestType",
    openDay: "vuint",
    chapterTextMapHash: "vuint",
    nameTextMapHash: "vuint",
    descTextMapHash: "vuint",
    preQuestId: "vuint",
    preOtherQuestIds: "vuint[]",
  },
}
