//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IrodoriFlowerGroupExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    groupId: "vuint",
  },
}
