//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IrodoriCardNumerical: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    cardNumericalModificationType: "IrodoriChessCardNumericalModificationType",
    cardNumericalModificationMode: "IrodoriChessCardNumericalModificationMode",
    cardNumericalModificationValue: "float",
  },
}
