//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const IrodoriChessLevelExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    levelId: "vuint",
    watcherList: "vuint[]",
    normalMapId: "vuint",
    hardMapId: "vuint",
    unlockHardScore: "vuint",
  },
}
