//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ItemUseConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    useOp: "ItemUseOp",
    useParam: "string[]",
  },
}
