//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const LampContributionExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    contribution: "vuint",
    rewardId: "vuint",
  },
}
