//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const LampRegionDataConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    region: "string",
    factor: "vuint",
  },
}
