//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const LanV2ProjectionStageExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    stageId: "vuint",
    titleTextMapHash: "vuint",
    descTextMapHash: "vuint",
    openDay: "vuint",
  },
}
