import { ConfigDefault } from "../"

export const LanV3BoatBaseExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    scheduleId: "vuint",
    FGHGCDNKJGI: "vuint[]",
    PFKHJFIOOIJ: "vuint[]",
    HPDBLDFELJB: "string",
    MAGDJGJHANI: "string",
    CILJPHCIBAC: "string",
    CEPJCHLMFKF: "string",
    IHEEOMCKOGI: "float",
    KJPJIPPEGBH: "vuint[]",
    IKOELPCIIIE: "vuint[]",
    NAFKKDMPJDA: "vuint[]",
    FKPCIPKBIJM: "vuint",
    ELJNCBGDADB: "float",
    preQuestId: "vuint",
    matchId: "vuint",
    draftId: "vuint",
    DGMDCBMJGGP: "vuint",
    EAILHJGAEOC: "vuint",
    JFJBDLPMINB: "string[]",
    FOOLGNIILPK: "string[]",
    GHBKGGPIDJF: "vuint",
    GEEGIKIMLLI: "string",
    BMKDEGAODPC: "string",
  },
}
