//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const LevelTagGroupsExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    ID: "vuint",
    levelTagGroupList: "LevelTagGroup[]",
    initialLevelTagIdList: "vuint[]",
    changeCd: "vuint",
  },
}
