//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const LevelTagGroup: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    levelTagIdList: "vuint[]",
  },
}
