//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const LocalizationExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    assetType: "LocalizationAssetType",
    defaultPath: "string",
    scPath: "string",
    tcPath: "string",
    enPath: "string",
    krPath: "string",
    jpPath: "string",
    esPath: "string",
    frPath: "string",
    idPath: "string",
    ptPath: "string",
    ruPath: "string",
    thPath: "string",
    viPath: "string",
    dePath: "string",
    trPath: "string",
    itPath: "string",
  },
}
