//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const LockTemplateExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "string",
    range: "float",
    combatPri: "float",
    normalPri: "float",
  },
}
