//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const LunaRiteSearchingExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    Id: "vuint",
    regionType: "LunaRiteRegionType",
    openDay: "vuint",
    progressWatcherID: "vuint",
    watcherID: "vuint[]",
    regionCenter: "float[]",
    regionNameHashSuffix: "vuint",
    regionNameHashPre: "byte",
    regionRadius: "float",
    chestCond: "vuint",
    runeCond: "vuint",
    chestMarkNum: "vuint",
    runeMarkNum: "vuint",
  },
}
