//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MainMonsterConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    boss: "vuint[]",
    monster: "vuint[]",
  },
}
