//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MainCoopExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    _HACK__1: "__HACK_",
    mainCoopCfg: "string",
    mainQuestSeries: "vuint",
  },
}
