//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MapAreaConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    sceneID: "vuint",
    name: "string",
    areaID_1: "vuint[]",
    scenePointID: "vuint",
    mapAreaState: "MapAreaState",
  },
}
