//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MapTagDataConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    type: "MapTagType",
    nameTextMapHash: "vuint",
    nameWithRubyTextTextMapHash: "vuint",
    sortID: "vuint",
    icon: "string",
    unlockByDefault: "bool",
    hideBeforeUnlock: "bool",
    cityID: "vuint",
    transPointID: "vuint",
    sceneIdList: "vuint[]",
    defaultLocateX: "float",
    defaultLocateZ: "float",
  },
}
