//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MatchCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "MatchLimitType",
    param: "vint",
  },
}
