//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MatchPunishExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    times: "vuint",
    punishTime: "vuint",
  },
}
