//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MechanicusWatcherExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: "WatcherConfig",
  Fields: {
    reward_tokens: "vuint",
    descTextMapHash: "vuint",
  },
}
