//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MichiaeWatcherExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    watcherId: "vuint",
    iconNameHashSuffix: "vuint",
    iconNameHashPre: "byte",
  },
}
