//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MichiaeErosionAreaExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    areaId: "vuint",
    A1: "float",
    A2: "float",
    A3: "float",
  },
}
