//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MonsterRelationshipExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    tagStr: "string",
    monsterRarity: "MonsterRarityType",
  },
}
