//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MonsterDrop: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    dropId: "vuint",
    hpPercent: "float",
  },
}
