//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MonsterConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    boss: "string[]",
    monster: "string[]",
  },
}
