//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MoonfinTrialExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    activityId: "vuint",
    levelIdList: "vuint[]",
    activityFishId: "vuint",
    activityFishGainLimit: "vuint",
    activityFishPoolId: "vuint",
    activityRewardPreviewId: "vuint",
    pushTipsId: "vuint",
    mainQuestList: "vuint[]",
    preconditionMainQuestIds: "vuint[]",
  },
}
