//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MpCrucibleRewardConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    dropID: "vuint",
    rewardId: "vuint",
    rewardPreview: "vuint",
  },
}
