//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MpPlayBuffExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    nameTextMapHash: "vuint",
    descTextMapHash: "vuint",
    icon: "string",
  },
}
