//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MultistageExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    stageType: "string",
    isMainGroupCanUnload: "bool",
  },
}
