//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const MusicInstrumentConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    instrumentID: "vuint",
    widgetID: "vuint",
    performID: "vint",
    freeModePerfabPath: "string",
  },
}
