//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const NewActivityCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "NewActivityCondType",
    param: "vint[]",
  },
}
