//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const NewActivityScoreShowExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    descTextMapHash: "vuint",
    score: "vuint",
  },
}
