//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const NightCrowArgumentExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    argumentId: "vuint",
    gadgetStateList: "vuint[]",
    posOffset: "string",
    rotation: "string",
    positionList: "string",
    limitPositionList: "string",
    limitCenterPosition: "string",
    GMEGCFAOEHE: "string",
    KICBPJDKPFD: "string",
    fov: "string",
  },
}
