import { ConfigDefault } from "../"

export const NpcExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: "EntityExcelConfig",
  Fields: {
    jsonName: "string",
    jsonPathHash: "vuint",
    alias: "string",
    scriptDataPath: "string",
    luaDataPath: "string",
    luaDataIndex: "vuint",
    hasCombat: "bool",
    hasMove: "bool",
    hasAudio: "bool",
    isDaily: "bool",
    dyePart: "string",
    billboardType: "BillboardType",
    billboardIcon: "string",
    invisiable: "bool",
    disableShowName: "bool",
    templateEmotionPath: "string",
    animatorConfigPathHash: "vuint",
    bodyType: "NPCBodyType",
    HGAKHIFOPGP: "NPCSpecialType",
    CIDIBNHBLDP: "vuint",
    AIGNBDLDFPI: "vuint",
    ALMNHHFHDDI: "vuint[]",
    EDMFJGGJICH: "vuint",
    OFPEEEOAOEG: "bool",
    BMKPBAICPMA: "bool",
    PNOAPLIEJNP: "bool",
    PIKGJJLGCKP: "bool",
    LAOCAEONEFO: "vuint",
    GNAJIFFGBNI: "ElementType",
  },
}
