//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const OfferingLumenStoneExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    configId: "vuint",
    level: "vuint",
    descSkillTextMapHash: "vuint",
    descDetailTextMapHash: "vuint",
    iconPath: "string",
  },
}
