//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const OfferingActionContent: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    actionType: "OfferingActionType",
    param: "string",
  },
}
