//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const OfferingOpenStateConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    offeringId: "vuint",
    openState: "OpenStateType",
    itemLimit: "ItemLimitType",
    isContinuousLevelUp: "bool",
    maxLevelLimitType: "OfferingMaxLevelLimitType",
    activityId: "vuint",
    isAllowHostInMpMode: "bool",
  },
}
