//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const OpenStateCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    cond_type: "OpenStateCondType",
    param: "vuint",
    param2: "vuint",
  },
}
