//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const OraionokamiDescExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    descId: "vuint",
    descContentTextMapHash: "vuint",
  },
}
