//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const PackageContentConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    materialId: "vuint",
    materialNum: "vuint",
  },
}
