//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const PlaceNameConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    mapTagType: "MapTagType",
    placeNameID: "string",
    conditionType: "PlaceNameConditionType",
    conditionParam1: "string",
    conditionParam2: "string",
    actionType: "PlaceNameActionType",
  },
}
