//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const PreviewActivityCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    condtionId: "vuint",
    desc: "string",
  },
}
