//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const PriceTierConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    tierName: "string",
    vipPoint: "vuint",
  },
}
