//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ProductPlayDetailConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: "ProductDetailConfig",
  Fields: {
    play_type: "ProductPlayType",
    itemNameTextMapHash: "vuint",
  },
}
