//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const PropValConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    propType: "FightPropType",
    value: "float",
  },
}
