//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ProudSkillOpenConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    proudSkillGroupId: "vuint",
    needAvatarPromoteLevel: "vuint",
  },
}
