//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const PSActivitiesSubTaskConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: "PSActivitiesBaseConfig",
  Fields: {
    taskID: "vuint",
    hidden: "bool",
  },
}
