//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const PushTipsConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    pushTipsId: "vuint",
    rewardId: "vuint",
    titleTextMapHash: "vuint",
    subtitleTextMapHash: "vuint",
    pushTipsType: "PushTipsType",
    showIcon: "string",
    tabIcon: "string",
    tutorialId: "vuint",
    codexType: "PushTipsCodexType",
    groupId: "vuint",
    showImmediately: "bool",
  },
}
