//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const QTEExec: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "QTEActionType",
    param: "vint[]",
  },
}
