//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const QuestSummarizationTextExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    Id: "vuint",
    DescTextMapHash: "vuint",
  },
}
