//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const QuestDialogDecoratorExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    decoratorContent: "string",
  },
}
