//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const QuestCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "QuestCondType",
    param: "vint[]",
  },
}
