//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const QuestGlobalVarConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    defaultValue: "vint",
  },
}
