//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const QuestElemSample: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "string",
    content: "string",
  },
}
