//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const QuestExec: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "QuestExecType",
    param: "string[]",
  },
}
