//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RadarHintExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    radarHintType: "RadarHintType",
    name: "string",
    radius: "float",
    offsetRadius: "float",
    areaRadius: "float",
    effectName: "string",
    iconName: "string",
    audioName: "string",
  },
}
