//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RandTaskDropConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    dropId: "vuint",
  },
}
