//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RandTaskRewardConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    ID: "vuint",
    dropVec: "RandTaskDropConfig[]",
  },
}
