//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RandomQuestCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "QuestCondType",
    param: "string[]",
  },
}
