//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RandomQuestFilterConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    filterType: "RandomQuestFilterType",
    filterFactor: "string",
    filterParamList: "vuint[]",
  },
}
