//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RandomItemConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    itemId: "vuint",
    count: "vuint",
    weight: "vuint",
  },
}
