//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RandomQuestContent: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "QuestContentType",
    param: "string[]",
    param_str: "string",
    count: "string",
  },
}
