import { ConfigDefault } from ".."

export const RandomQuestExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    subId: "vuint",
    mainId: "vuint",
    order: "vint",
    subIdSet: "vuint",
    titleTextMapHash: "vuint",
    descTextMapHash: "vuint",
    showType: "QuestShowType",
    acceptCondComb: "LogicType",
    acceptCond: "RandomQuestCond[]",
    finishCondComb: "LogicType",
    finishCond: "RandomQuestContent[]",
    failCondComb: "LogicType",
    failCond: "RandomQuestContent[]",
    guide: "QuestGuide",
    showGuide: "ShowQuestGuideType",
    guideHint: "QuestGuideHintEx",
    finishParent: "bool",
    failParent: "bool",
    failParentShow: "QuestShowType",
    isRewind: "bool",
    awardItems: "IdCountConfig[]",
    beginExec: "QuestExec[]",
    finishExec: "QuestExec[]",
    failExec: "QuestExec[]",
    exclusiveNpcPriority: "vuint",
    banType: "BanGroupType",
  },
}
