//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RandomQuestElem: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    name: "string[]",
    poolId: "vuint",
  },
}
