//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RefreshIndexExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    priority: "vuint",
    type: "RefreshIndexType",
    rarity: "MonsterRarityType",
    name: "string",
    _HACK__4: "__HACK_",
    refreshId: "vuint",
  },
}
