//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RefreshPolicyExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    type: "RefreshType",
    time: "string",
  },
}
