//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RegionSearchCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "RegionSearchCondType",
    param: "vint[]",
  },
}
