//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ReliquarySetExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    setId: "vuint",
    setIcon: "string",
    setNeedNum: "vuint[]",
    EquipAffixId: "vuint",
    DisableFilter: "vuint",
    containsList: "vuint[]",
    bagSortValue: "vuint",
  },
}
