//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ReliquaryAffixExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    depot_id: "vuint",
    group_id: "vuint",
    propType: "FightPropType",
    propValue: "float",
  },
}
