//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ReliquaryPowerupExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    powerupMultiple: "vuint",
  },
}
