//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ReminderExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    speakerTextMapHash: "vuint",
    contentTextMapHash: "vuint",
    delay: "float",
    showTime: "float",
    nextReminderId: "vuint",
    soundEffect: "string",
    style: "ReminderStyleType",
    hasAudio: "bool",
  },
}
