//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ReputationEntranceCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "ReputationEntranceCondType",
    param1: "vuint",
    param2: "vuint",
  },
}
