//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ReputationExploreExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    exploreId: "vuint",
    cityId: "vuint",
    exploreProgress: "vuint",
    rewardId: "vuint",
    conditionTextTextMapHash: "vuint",
  },
}
