//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ReunionCommercialExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    domesticLink: "string",
    overseaLink: "string",
  },
}
