//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ReunionPrivilegeConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "ReunionPrivilegeType",
    sub_type: "string",
  },
}
