//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RewardItemConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    itemId: "vuint",
    itemCount: "vuint",
  },
}
