//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RogueDiaryRoundExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    RoomCount: "vuint",
    roundRoomConfigList: "vuint[]",
    hpCorrection: "vuint",
  },
}
