//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RoguelikeShikigamiUnlockConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "RoguelikeShikigamiUnlockType",
    param: "string",
  },
}
