//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RogueCellWeightExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    springWeight: "vuint",
    storeWeight: "vuint",
    eliteWeight: "vuint",
  },
}
