//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RogueGadgetRotConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    dir: "RogueGadgetDirType",
    rotation: "vuint",
  },
}
