//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RogueDiaryQuestExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    activityId: "vuint",
    questIdList: "string[]",
    condIdList: "vuint[]",
    watcherIdList: "vuint[]",
  },
}
