//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RogueSequenceCellConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "RogueCellType",
    range: "vuint[]",
  },
}
