//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RogueDiaryRoomTypeConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    normalRoomConfigList: "vuint[]",
    hardRoomConfigList: "vuint[]",
  },
}
