//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RogueGadgetStateConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    state: "RogueGadgetStateType",
    gadgetState: "vuint",
  },
}
