//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RoguelikeRuneExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    isDefaultUnlock: "bool",
    nameTextMapHash: "vuint",
    descTextMapHash: "vuint",
    runeIcon: "string",
    runeIcon1: "string",
    runeIcon2: "string",
    runeIcon3: "string",
    defaultUseCount: "vuint",
    elementType: "vuint",
    abilityName: "string",
  },
}
