//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RogueDiaryResourceExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    type: "RogueDiaryResourceType",
    value: "vuint",
  },
}
