//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const RoomExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    _HACK__1: "__HACK_",
    prefabPath: "string",
    navMeshPath: "string",
  },
}
