//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SalvageTypeDataExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    playType: "SalvagePlayType",
  },
}
