//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SceneTagCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    condType: "SceneTagCondType",
    param1: "vint",
    param2: "vint",
  },
}
