//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SceneExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    type: "SceneType",
    subtype: "SceneSubType",
    ignoreNavMesh: "bool",
    navmeshMode: "NavmeshModeType",
    scriptData: "string",
    overrideDefaultProfile: "string",
    levelEntityConfig: "string",
    entityAppearSorted: "vuint",
    specifiedAvatarList: "vuint[]",
    maxSpecifiedAvatarNum: "vuint",
    sceneFixTime: "float",
    comment: "string",
    safePoint: "vuint",
    mpType: "SceneMpType",
    isAllowMapMarkPoint: "bool",
    isDeleteMapMarkPoint: "bool",
    dungeonEntryPoint: "vuint[]",
  },
}
