//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SGVConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    key: "string",
    value: "float",
  },
}
