//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ShopmallRecommendCond: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "ShopmallRecommendCondType",
    param1Str: "string",
    param2Str: "string",
    param1: "vuint",
    param2: "vuint",
  },
}
