//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const ShopRotateExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    rotateId: "vuint",
    itemId: "vuint",
    rotateOrder: "vuint",
  },
}
