//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SignInCondConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "SignInCondType",
    paramList: "vint[]",
  },
}
