//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SignInCondExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    configId: "vuint",
    condComb: "LogicType",
    condList: "SignInCondConfig[]",
    totalDayCount: "vuint",
  },
}
