//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SoloConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    soloStart: "vuint",
    soloEnd: "vuint",
    isSelf: "bool",
  },
}
