//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SourceJumpConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    jumpType: "SourceJumpType",
    jumpParam: "vuint",
  },
}
