//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const StateExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    stateName: "string",
    stateType: "StateType",
    rank: "vuint",
  },
}
