//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const SystemOpenUIConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    nameTextMapHash: "vuint",
    icon_path: "string",
    descTextMapHash: "vuint",
    tutorial_id: "vuint",
  },
}
