//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TalkExec: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "TalkExecType",
    param: "string[]",
  },
}
