//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TauntLevelTemplateExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "TauntLevel",
    tauntLevelVal: "vuint",
  },
}
