import { ConfigDefault } from "../"

export const TODO_GalleryExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    type: "GalleryType",
    param: "string[]",
    isEnableSinglePrepare: "bool",
    singlePrepareTime: "vuint",
    isEnableMpPrepare: "bool",
    mpPrepareTime: "vuint",
    isPermitInputInPrepare: "bool",
    canInterruptByClient: "bool",
    sceneId: "vuint",
    controlGroupId: "vuint",
    groupId: "vuint[]",
    groupFurnitureId: "vuint",
    revivePointGroupId: "vuint",
    revivePointConfigId: "vuint",
    abilityGroup: "string",
    abilityGroupList: "string[]",
    limitRegion: "string",
    centerSceneId: "vuint",
    centerPosList: "float[]",
    centerRadius: "vuint",
    duration: "vuint",
    nameTextMapHash: "vuint",
    descTextMapHash: "vuint",
    galleryNameTextMapHash: "vuint",
    galleryMSGTextMapHash: "vuint",
    pic: "string",
    targetTextMapHash: "vuint",
    startAudioValues: "string",
    endAudioValues: "string",
    selectable_ability_groups: "string[]",
    teamAbilityGroupList: "string[]",
    selectableTeamAbilityGroupList: "string[]",
    isDisableGroupDefaultReviseLevel: "bool",
    successGalleryStopReasons: "vuint[]",
  },
}
