import { ConfigDefault } from "../"

export const TODO_HomeWorldFurnitureExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: "ItemConfig",
  Fields: {
    furnitureGadgetID: "vuint[]",
    furnType: "vuint[]",
    surfaceType: "FurnitureDeploySurfaceType",
    arrangeLimit: "vuint",
    isSpecialFurniture: "vuint",
    specialFurnitureType: "SpeicalFurnitureType",
    roomSceneID: "vuint",
    gridStyle: "vuint",
    comfort: "vuint",
    stackLimit: "vuint",
    cost: "vuint",
    discountCost: "vuint",
    isCombinableLight: "vuint",
    height: "float",
    canFloat: "vuint",
    isUnique: "vuint",
    itemIcon: "string",
    effectIcon: "string",
    clampDistance: "float",
    editorClampDistance: "float",
    deployGlitchIndex: "vuint",
    rankLevel: "vuint",
    jsonName: "string",
    pushTipsId: "vuint",
    NNMOCBGPNDB: "bool",
    groupRecordType: "GroupRecordType",
  },
}
