//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TowerStarReward: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    minStarCount: "vuint",
    rewardId: "vuint",
  },
}
