//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TowerCondition: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    towerCondType: "TowerCondType",
    argumentListUpper: "vuint[]",
    argumentList: "vuint[]",
  },
}
