//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TowerSchedule: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    floorList: "vuint[]",
    openTime: "string",
  },
}
