//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TreeDropExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    treeType: "TreeType",
    dropId: "vuint",
  },
}
