//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const TrialAvatarExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    trialAvatarId: "vuint",
    trialAvatarParamList: "vuint[]",
    trialSkillDepotId: "vuint",
    isDynamicLevel: "bool",
    specified_costume_id: "vuint",
  },
}
