//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const UidOpNotifyExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    contentTextMapHash: "vuint",
  },
}
