//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const WatcherTriggerConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    triggerType: "WatcherTriggerType",
    paramList: "string[]",
  },
}
