//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const WatcherPredicateConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    predicateType: "WatcherPredicateType",
    paramList: "vuint[]",
  },
}
