//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const WeaponLevelExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    level: "vuint",
    requiredExps: "vuint[]",
  },
}
