//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const WeaponProperty: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    propType: "FightPropType",
    initValue: "float",
    type: "GrowCurveType",
  },
}
