//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const WinterCampBattleExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    openDay: "vuint",
    priority: "vuint",
    groupLinkID: "vuint",
    challengeIndex: "vuint",
    rewardID: "vuint",
  },
}
