//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const WinterCampDropGroup: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    dropId: "vuint[]",
  },
}
