//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const WinterCampSnowmanDetailExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    snowmanNameTextMapHash: "vuint",
    snowmanDescTextMapHash: "vuint",
    unlockCondId: "vuint",
    unlockTextTextMapHash: "vuint",
    watcherId: "vuint",
  },
}
