//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const WinterCampRaceItemTipsExcelConfig: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    id: "vuint",
    icon: "string",
    titleTextMapHash: "vuint",
    descTextMapHash: "vuint",
  },
}
