//Auto Generated by ConfigParser
import { ConfigDefault } from ".."

export const WorldAreaLevelupAction: ConfigDefault = {
  attribute: ["excel"],
  baseClass: null,
  Fields: {
    type: "WorldAreaLevelupActionType",
    param1_vec: "vuint[]",
    param2_vec: "vuint[]",
  },
}
